	@ src/berry_blender.c:919 berry_blender_line_919 (+2 aliases)
	.globl gText_Rom_5C983E
gText_Rom_5C983E: @ 0x085C983E
	.string "からい$"
	.if (. - gText_Rom_5C983E) > 0x4
	.error "gText_Rom_5C983E may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5C983E) < 0x4
	.space 0x4 - (. - gText_Rom_5C983E)
	.endif
	.globl gUnknown_85C9842
gUnknown_85C9842: @ 0x085C9842

	@ src/berry_blender.c:919 berry_blender_line_919 (+2 aliases)
	.globl gText_Rom_5C9842
gText_Rom_5C9842: @ 0x085C9842
	.string "しぶい$"
	.if (. - gText_Rom_5C9842) > 0x4
	.error "gText_Rom_5C9842 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5C9842) < 0x4
	.space 0x4 - (. - gText_Rom_5C9842)
	.endif
	.globl gUnknown_85C9846
gUnknown_85C9846: @ 0x085C9846

	@ src/berry_blender.c:919 berry_blender_line_919 (+3 aliases)
	.globl gText_Rom_5C9846
gText_Rom_5C9846: @ 0x085C9846
	.string "あまい$"
	.if (. - gText_Rom_5C9846) > 0x4
	.error "gText_Rom_5C9846 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5C9846) < 0x4
	.space 0x4 - (. - gText_Rom_5C9846)
	.endif
	.globl gUnknown_85C984A
gUnknown_85C984A: @ 0x085C984A

	@ src/berry_blender.c:919 berry_blender_line_919 (+2 aliases)
	.globl gText_Rom_5C984A
gText_Rom_5C984A: @ 0x085C984A
	.string "にがい$"
	.if (. - gText_Rom_5C984A) > 0x4
	.error "gText_Rom_5C984A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5C984A) < 0x4
	.space 0x4 - (. - gText_Rom_5C984A)
	.endif
	.globl gUnknown_85C984E
gUnknown_85C984E: @ 0x085C984E

	@ src/berry_blender.c:919 berry_blender_line_919 (+2 aliases)
	.globl gText_Rom_5C984E
gText_Rom_5C984E: @ 0x085C984E
	.string "すっぱい$"
	.if (. - gText_Rom_5C984E) > 0x5
	.error "gText_Rom_5C984E may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5C984E) < 0x5
	.space 0x5 - (. - gText_Rom_5C984E)
	.endif

	@ src/data/easy_chat/easy_chat_group_conditions.h:100 easy_chat_group_conditions_line_100
	.globl gText_Rom_5C9853
gText_Rom_5C9853: @ 0x085C9853
	.string "うまい$"
	.if (. - gText_Rom_5C9853) > 0x4
	.error "gText_Rom_5C9853 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5C9853) < 0x4
	.space 0x4 - (. - gText_Rom_5C9853)
	.endif
	@ Replaced baserom.gba range: offset=0x5C9857, size=0x5
	.byte 0x0A, 0x1F, 0x06, 0x0B, 0xFF
	.globl gUnknown_85C985C
gUnknown_85C985C: @ 0x085C985C

