	@ pret/pokeemerald-jp direct xref for 0x085CA388: pokemon_summary_screen.s: sub_081C21CC
	.globl gPokemonSummaryScreenData_085CA388
gPokemonSummaryScreenData_085CA388:
	.globl gPokemonSummaryScreenData_085CA388
	@ analyzed canonical ROM range 0x085CA388-0x085CA38A
	@ structured u8 payload; no safe higher-level semantic type was provable
	@ ANALYSIS: U8_DATA size=0x3 bytes=3
	.byte 0xC2, 0xCA, 0xFF
	@ pret/pokeemerald-jp direct xref for 0x085CA38B: pokemon_summary_screen.s: PrintExpPointsNextLevel
	.globl gPokemonSummaryScreenData_085CA38B
gPokemonSummaryScreenData_085CA38B: @ 0x085CA38B
	@ analyzed canonical ROM range 0x085CA38B-0x085CA38D
	@ structured u8 payload; no safe higher-level semantic type was provable
	@ ANALYSIS: U8_DATA size=0x3 bytes=3
	.byte 0x01, 0x14, 0xFF
	.globl gText_Rom_5CA38E
