	.globl gUnknown_82D254C
gUnknown_82D254C: @ 0x082D254C
	@ Replaced baserom.gba range: offset=0x2D254C, size=0xC
	.byte 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
	.globl gUnknown_82D2558
gUnknown_82D2558: @ 0x082D2558
	@ Resolved pointer table; original ROM range 0x2D2558..0x2D2587.
	.4byte PSR_SYS_MODE
	.4byte MAP_NUM_ROUTE113
	.4byte PSR_SYS_MODE
	.4byte MAP_NUM_ROUTE115
	.4byte PSR_SYS_MODE
	.4byte MAP_NUM_ROUTE115
	.4byte PSR_SYS_MODE
	.4byte PSR_SYS_MODE
	.4byte MAP_NUM_ROUTE115
	.4byte PSR_SYS_MODE
	.4byte MAP_NUM_ROUTE115
	.4byte PSR_SYS_MODE
