	@ src/data/easy_chat/easy_chat_group_actions.h:10 easy_chat_group_actions_line_10
	.globl gText_Rom_5770F3
gText_Rom_5770F3: @ 0x085770F3
	.string "あきらめ{EOS}"
	.if (. - gText_Rom_5770F3) > 0x5
	.error "gText_Rom_5770F3 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5770F3) < 0x5
	.space 0x5 - (. - gText_Rom_5770F3)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5770F8
gText_Rom_5770F8: @ 0x085770F8
	.string "あげる{EOS}"
	.if (. - gText_Rom_5770F8) > 0x4
	.error "gText_Rom_5770F8 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5770F8) < 0x4
	.space 0x4 - (. - gText_Rom_5770F8)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:22 easy_chat_group_actions_line_22
	.globl gText_Rom_5770FC
gText_Rom_5770FC: @ 0x085770FC
	.string "あせる{EOS}"
	.if (. - gText_Rom_5770FC) > 0x4
	.error "gText_Rom_5770FC may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5770FC) < 0x4
	.space 0x4 - (. - gText_Rom_5770FC)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:28 easy_chat_group_actions_line_28
	.globl gText_Rom_577100
gText_Rom_577100: @ 0x08577100
	.string "あそび{EOS}"
	.if (. - gText_Rom_577100) > 0x4
	.error "gText_Rom_577100 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577100) < 0x4
	.space 0x4 - (. - gText_Rom_577100)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:34 easy_chat_group_actions_line_34
	.globl gText_Rom_577104
gText_Rom_577104: @ 0x08577104
	.string "あそぶ{EOS}"
	.if (. - gText_Rom_577104) > 0x4
	.error "gText_Rom_577104 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577104) < 0x4
	.space 0x4 - (. - gText_Rom_577104)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:40 easy_chat_group_actions_line_40
	.globl gText_Rom_577108
gText_Rom_577108: @ 0x08577108
	.string "あつめ{EOS}"
	.if (. - gText_Rom_577108) > 0x4
	.error "gText_Rom_577108 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577108) < 0x4
	.space 0x4 - (. - gText_Rom_577108)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:46 easy_chat_group_actions_line_46
	.globl gText_Rom_57710C
gText_Rom_57710C: @ 0x0857710C
	.string "あるき{EOS}"
	.if (. - gText_Rom_57710C) > 0x4
	.error "gText_Rom_57710C may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57710C) < 0x4
	.space 0x4 - (. - gText_Rom_57710C)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:52 easy_chat_group_actions_line_52
	.globl gText_Rom_577110
gText_Rom_577110: @ 0x08577110
	.string "あるく{EOS}"
	.if (. - gText_Rom_577110) > 0x4
	.error "gText_Rom_577110 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577110) < 0x4
	.space 0x4 - (. - gText_Rom_577110)
	.endif
	@ Decoded text from ROM range: offset=0x577114, size=0x6
	.string "いう{EOS}"
	.string "いく{EOS}"

	@ src/data/easy_chat/easy_chat_group_actions.h:70 easy_chat_group_actions_line_70
	.globl gText_Rom_57711A
gText_Rom_57711A: @ 0x0857711A
	.string "いって{EOS}"
	.if (. - gText_Rom_57711A) > 0x4
	.error "gText_Rom_57711A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57711A) < 0x4
	.space 0x4 - (. - gText_Rom_57711A)
	.endif
	@ Decoded text from ROM range: offset=0x57711E, size=0x3
	.string "おき{EOS}"

	@ src/data/easy_chat/easy_chat_group_actions.h:82 easy_chat_group_actions_line_82
	.globl gText_Rom_577121
gText_Rom_577121: @ 0x08577121
	.string "おこり{EOS}"
	.if (. - gText_Rom_577121) > 0x4
	.error "gText_Rom_577121 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577121) < 0x4
	.space 0x4 - (. - gText_Rom_577121)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:88 easy_chat_group_actions_line_88
	.globl gText_Rom_577125
gText_Rom_577125: @ 0x08577125
	.string "おこる{EOS}"
	.if (. - gText_Rom_577125) > 0x4
	.error "gText_Rom_577125 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577125) < 0x4
	.space 0x4 - (. - gText_Rom_577125)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:94 easy_chat_group_actions_line_94
	.globl gText_Rom_577129
gText_Rom_577129: @ 0x08577129
	.string "おしえ{EOS}"
	.if (. - gText_Rom_577129) > 0x4
	.error "gText_Rom_577129 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577129) < 0x4
	.space 0x4 - (. - gText_Rom_577129)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:100 easy_chat_group_actions_line_100
	.globl gText_Rom_57712D
gText_Rom_57712D: @ 0x0857712D
	.string "おしえて{EOS}"
	.if (. - gText_Rom_57712D) > 0x5
	.error "gText_Rom_57712D may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57712D) < 0x5
	.space 0x5 - (. - gText_Rom_57712D)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:106 easy_chat_group_actions_line_106
	.globl gText_Rom_577132
gText_Rom_577132: @ 0x08577132
	.string "おねがい{EOS}"
	.if (. - gText_Rom_577132) > 0x5
	.error "gText_Rom_577132 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577132) < 0x5
	.space 0x5 - (. - gText_Rom_577132)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:112 easy_chat_group_actions_line_112
	.globl gText_Rom_577137
gText_Rom_577137: @ 0x08577137
	.string "おぼえ{EOS}"
	.if (. - gText_Rom_577137) > 0x4
	.error "gText_Rom_577137 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_577137) < 0x4
	.space 0x4 - (. - gText_Rom_577137)
	.endif

	@ src/data/easy_chat/easy_chat_group_actions.h:118 easy_chat_group_actions_line_118
	.globl gText_Rom_57713B
gText_Rom_57713B: @ 0x0857713B
	.string "かえる{EOS}"
	.if (. - gText_Rom_57713B) > 0x4
	.error "gText_Rom_57713B may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57713B) < 0x4
	.space 0x4 - (. - gText_Rom_57713B)
	.endif

