	@ asm/dodrio_berry_picking.s:10242 sub_080293D4
	.globl gText_Rom_5CCD77
gText_Rom_5CCD77: @ 0x085CCD77
	.string "1:{EOS}"
	.if (. - gText_Rom_5CCD77) > 0x3
	.error "gText_Rom_5CCD77 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5CCD77) < 0x3
	.space 0x3 - (. - gText_Rom_5CCD77)
	.endif

	@ asm/dodrio_berry_picking.s:10242 sub_080293D4 (+1 aliases)
	.globl gText_Rom_5CCD7A
gText_Rom_5CCD7A: @ 0x085CCD7A
	.string "2:{EOS}"
	.if (. - gText_Rom_5CCD7A) > 0x3
	.error "gText_Rom_5CCD7A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5CCD7A) < 0x3
	.space 0x3 - (. - gText_Rom_5CCD7A)
	.endif

	@ asm/dodrio_berry_picking.s:10242 sub_080293D4 (+1 aliases)
	.globl gText_Rom_5CCD7D
gText_Rom_5CCD7D: @ 0x085CCD7D
	.string "3:{EOS}"
	.if (. - gText_Rom_5CCD7D) > 0x3
	.error "gText_Rom_5CCD7D may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5CCD7D) < 0x3
	.space 0x3 - (. - gText_Rom_5CCD7D)
	.endif

	@ asm/dodrio_berry_picking.s:10242 sub_080293D4 (+1 aliases)
	.globl gText_Rom_5CCD80
gText_Rom_5CCD80: @ 0x085CCD80
	.string "4:{EOS}"
	.if (. - gText_Rom_5CCD80) > 0x3
	.error "gText_Rom_5CCD80 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5CCD80) < 0x3
	.space 0x3 - (. - gText_Rom_5CCD80)
	.endif

	@ asm/dodrio_berry_picking.s:10242 sub_080293D4 (+1 aliases)
	.globl gText_Rom_5CCD83
gText_Rom_5CCD83: @ 0x085CCD83
	.string "5:{EOS}"
	.if (. - gText_Rom_5CCD83) > 0x3
	.error "gText_Rom_5CCD83 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5CCD83) < 0x3
	.space 0x3 - (. - gText_Rom_5CCD83)
	.endif
