@ MAP_DESERT_UNDERPASS
@ ROM 0x0852D71C-0x0852D754

gDesertUnderpass_LandMons::
	wildmon 38, 38, SPECIES_DITTO
	wildmon 35, 35, SPECIES_WHISMUR
	wildmon 40, 40, SPECIES_DITTO
	wildmon 40, 40, SPECIES_LOUDRED
	wildmon 41, 41, SPECIES_DITTO
	wildmon 36, 36, SPECIES_WHISMUR
	wildmon 38, 38, SPECIES_LOUDRED
	wildmon 42, 42, SPECIES_DITTO
	wildmon 38, 38, SPECIES_WHISMUR
	wildmon 43, 43, SPECIES_DITTO
	wildmon 44, 44, SPECIES_LOUDRED
	wildmon 45, 45, SPECIES_DITTO

gDesertUnderpass_LandMonsInfo::
	wildmoninfo 10, gDesertUnderpass_LandMons
