@ MAP_FIERY_PATH
@ ROM 0x0852BCA4-0x0852BCDC

gFieryPath_LandMons::
	wildmon 15, 15, SPECIES_NUMEL
	wildmon 15, 15, SPECIES_KOFFING
	wildmon 16, 16, SPECIES_NUMEL
	wildmon 15, 15, SPECIES_MACHOP
	wildmon 15, 15, SPECIES_TORKOAL
	wildmon 15, 15, SPECIES_SLUGMA
	wildmon 16, 16, SPECIES_KOFFING
	wildmon 16, 16, SPECIES_MACHOP
	wildmon 14, 14, SPECIES_TORKOAL
	wildmon 16, 16, SPECIES_TORKOAL
	wildmon 14, 14, SPECIES_GRIMER
	wildmon 14, 14, SPECIES_GRIMER

gFieryPath_LandMonsInfo::
	wildmoninfo 10, gFieryPath_LandMons
