@ MAP_GRANITE_CAVE_STEVENS_ROOM
@ ROM 0x0852C368-0x0852C3A0

gGraniteCave_StevensRoom_LandMons::
	wildmon 7, 7, SPECIES_ZUBAT
	wildmon 8, 8, SPECIES_MAKUHITA
	wildmon 7, 7, SPECIES_MAKUHITA
	wildmon 8, 8, SPECIES_ZUBAT
	wildmon 9, 9, SPECIES_MAKUHITA
	wildmon 8, 8, SPECIES_ABRA
	wildmon 10, 10, SPECIES_MAKUHITA
	wildmon 6, 6, SPECIES_MAKUHITA
	wildmon 7, 7, SPECIES_ARON
	wildmon 8, 8, SPECIES_ARON
	wildmon 7, 7, SPECIES_ARON
	wildmon 8, 8, SPECIES_ARON

gGraniteCave_StevensRoom_LandMonsInfo::
	wildmoninfo 10, gGraniteCave_StevensRoom_LandMons
