@ MAP_GRANITE_CAVE_B1F
@ ROM 0x0852BB08-0x0852BB40

gGraniteCave_B1F_LandMons::
	wildmon 9, 9, SPECIES_ZUBAT
	wildmon 10, 10, SPECIES_ARON
	wildmon 9, 9, SPECIES_ARON
	wildmon 11, 11, SPECIES_ARON
	wildmon 10, 10, SPECIES_ZUBAT
	wildmon 9, 9, SPECIES_ABRA
	wildmon 10, 10, SPECIES_MAKUHITA
	wildmon 11, 11, SPECIES_MAKUHITA
	wildmon 10, 10, SPECIES_SABLEYE
	wildmon 10, 10, SPECIES_SABLEYE
	wildmon 9, 9, SPECIES_SABLEYE
	wildmon 11, 11, SPECIES_SABLEYE

gGraniteCave_B1F_LandMonsInfo::
	wildmoninfo 10, gGraniteCave_B1F_LandMons
