@ MAP_GRANITE_CAVE_1F
@ ROM 0x0852BAD0-0x0852BB08

gGraniteCave_1F_LandMons::
	wildmon 7, 7, SPECIES_ZUBAT
	wildmon 8, 8, SPECIES_MAKUHITA
	wildmon 7, 7, SPECIES_MAKUHITA
	wildmon 8, 8, SPECIES_ZUBAT
	wildmon 9, 9, SPECIES_MAKUHITA
	wildmon 8, 8, SPECIES_ABRA
	wildmon 10, 10, SPECIES_MAKUHITA
	wildmon 6, 6, SPECIES_MAKUHITA
	wildmon 7, 7, SPECIES_GEODUDE
	wildmon 8, 8, SPECIES_GEODUDE
	wildmon 6, 6, SPECIES_GEODUDE
	wildmon 9, 9, SPECIES_GEODUDE

gGraniteCave_1F_LandMonsInfo::
	wildmoninfo 10, gGraniteCave_1F_LandMons
