@ MAP_METEOR_FALLS_B1F_1R
@ ROM 0x0852CE4C-0x0852CED0

gMeteorFalls_B1F_1R_LandMons::
	wildmon 33, 33, SPECIES_GOLBAT
	wildmon 35, 35, SPECIES_GOLBAT
	wildmon 33, 33, SPECIES_GOLBAT
	wildmon 35, 35, SPECIES_SOLROCK
	wildmon 33, 33, SPECIES_SOLROCK
	wildmon 37, 37, SPECIES_SOLROCK
	wildmon 35, 35, SPECIES_GOLBAT
	wildmon 39, 39, SPECIES_SOLROCK
	wildmon 38, 38, SPECIES_GOLBAT
	wildmon 40, 40, SPECIES_GOLBAT
	wildmon 38, 38, SPECIES_GOLBAT
	wildmon 40, 40, SPECIES_GOLBAT

gMeteorFalls_B1F_1R_LandMonsInfo::
	wildmoninfo 10, gMeteorFalls_B1F_1R_LandMons

gMeteorFalls_B1F_1R_WaterMons::
	wildmon 30, 35, SPECIES_GOLBAT
	wildmon 30, 35, SPECIES_GOLBAT
	wildmon 25, 35, SPECIES_SOLROCK
	wildmon 15, 25, SPECIES_SOLROCK
	wildmon 5, 15, SPECIES_SOLROCK

gMeteorFalls_B1F_1R_WaterMonsInfo::
	wildmoninfo 4, gMeteorFalls_B1F_1R_WaterMons

gMeteorFalls_B1F_1R_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_GOLDEEN
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_GOLDEEN
	wildmon 10, 30, SPECIES_BARBOACH
	wildmon 25, 30, SPECIES_BARBOACH
	wildmon 30, 35, SPECIES_BARBOACH
	wildmon 30, 35, SPECIES_WHISCASH
	wildmon 35, 40, SPECIES_WHISCASH
	wildmon 40, 45, SPECIES_WHISCASH

gMeteorFalls_B1F_1R_FishingMonsInfo::
	wildmoninfo 30, gMeteorFalls_B1F_1R_FishingMons
