@ MAP_METEOR_FALLS_STEVENS_CAVE
@ ROM 0x0852D9BC-0x0852D9F4

gMeteorFalls_StevensCave_LandMons::
	wildmon 33, 33, SPECIES_GOLBAT
	wildmon 35, 35, SPECIES_GOLBAT
	wildmon 33, 33, SPECIES_GOLBAT
	wildmon 35, 35, SPECIES_SOLROCK
	wildmon 33, 33, SPECIES_SOLROCK
	wildmon 37, 37, SPECIES_SOLROCK
	wildmon 35, 35, SPECIES_GOLBAT
	wildmon 39, 39, SPECIES_SOLROCK
	wildmon 38, 38, SPECIES_GOLBAT
	wildmon 40, 40, SPECIES_GOLBAT
	wildmon 38, 38, SPECIES_GOLBAT
	wildmon 40, 40, SPECIES_GOLBAT

gMeteorFalls_StevensCave_LandMonsInfo::
	wildmoninfo 10, gMeteorFalls_StevensCave_LandMons
