@ MAP_MT_PYRE_EXTERIOR
@ ROM 0x0852C2F8-0x0852C330

gMtPyre_Exterior_LandMons::
	wildmon 27, 27, SPECIES_SHUPPET
	wildmon 27, 27, SPECIES_SHUPPET
	wildmon 28, 28, SPECIES_SHUPPET
	wildmon 29, 29, SPECIES_SHUPPET
	wildmon 29, 29, SPECIES_VULPIX
	wildmon 27, 27, SPECIES_VULPIX
	wildmon 29, 29, SPECIES_VULPIX
	wildmon 25, 25, SPECIES_VULPIX
	wildmon 27, 27, SPECIES_WINGULL
	wildmon 27, 27, SPECIES_WINGULL
	wildmon 26, 26, SPECIES_WINGULL
	wildmon 28, 28, SPECIES_WINGULL

gMtPyre_Exterior_LandMonsInfo::
	wildmoninfo 10, gMtPyre_Exterior_LandMons
