@ MAP_MT_PYRE_SUMMIT
@ ROM 0x0852C330-0x0852C368

gMtPyre_Summit_LandMons::
	wildmon 28, 28, SPECIES_SHUPPET
	wildmon 29, 29, SPECIES_SHUPPET
	wildmon 27, 27, SPECIES_SHUPPET
	wildmon 26, 26, SPECIES_SHUPPET
	wildmon 30, 30, SPECIES_SHUPPET
	wildmon 25, 25, SPECIES_SHUPPET
	wildmon 24, 24, SPECIES_SHUPPET
	wildmon 28, 28, SPECIES_DUSKULL
	wildmon 26, 26, SPECIES_DUSKULL
	wildmon 30, 30, SPECIES_DUSKULL
	wildmon 28, 28, SPECIES_CHIMECHO
	wildmon 28, 28, SPECIES_CHIMECHO

gMtPyre_Summit_LandMonsInfo::
	wildmoninfo 10, gMtPyre_Summit_LandMons
