@ MAP_NEW_MAUVILLE_ENTRANCE
@ ROM 0x0852CAD8-0x0852CB10

gNewMauville_Entrance_LandMons::
	wildmon 24, 24, SPECIES_VOLTORB
	wildmon 24, 24, SPECIES_MAGNEMITE
	wildmon 25, 25, SPECIES_VOLTORB
	wildmon 25, 25, SPECIES_MAGNEMITE
	wildmon 23, 23, SPECIES_VOLTORB
	wildmon 23, 23, SPECIES_MAGNEMITE
	wildmon 26, 26, SPECIES_VOLTORB
	wildmon 26, 26, SPECIES_MAGNEMITE
	wildmon 22, 22, SPECIES_VOLTORB
	wildmon 22, 22, SPECIES_MAGNEMITE
	wildmon 22, 22, SPECIES_VOLTORB
	wildmon 22, 22, SPECIES_MAGNEMITE

gNewMauville_Entrance_LandMonsInfo::
	wildmoninfo 10, gNewMauville_Entrance_LandMons
