@ MAP_PETALBURG_CITY
@ ROM 0x0852D210-0x0852D25C

gPetalburgCity_WaterMons::
	wildmon 20, 30, SPECIES_MARILL
	wildmon 10, 20, SPECIES_MARILL
	wildmon 30, 35, SPECIES_MARILL
	wildmon 5, 10, SPECIES_MARILL
	wildmon 5, 10, SPECIES_MARILL

gPetalburgCity_WaterMonsInfo::
	wildmoninfo 1, gPetalburgCity_WaterMons

gPetalburgCity_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_GOLDEEN
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_GOLDEEN
	wildmon 10, 30, SPECIES_CORPHISH
	wildmon 25, 30, SPECIES_CORPHISH
	wildmon 30, 35, SPECIES_CORPHISH
	wildmon 20, 25, SPECIES_CORPHISH
	wildmon 35, 40, SPECIES_CORPHISH
	wildmon 40, 45, SPECIES_CORPHISH

gPetalburgCity_FishingMonsInfo::
	wildmoninfo 10, gPetalburgCity_FishingMons
