@ MAP_PETALBURG_WOODS
@ ROM 0x0852BA60-0x0852BA98

gPetalburgWoods_LandMons::
	wildmon 5, 5, SPECIES_POOCHYENA
	wildmon 5, 5, SPECIES_WURMPLE
	wildmon 5, 5, SPECIES_SHROOMISH
	wildmon 6, 6, SPECIES_POOCHYENA
	wildmon 5, 5, SPECIES_SILCOON
	wildmon 5, 5, SPECIES_CASCOON
	wildmon 6, 6, SPECIES_WURMPLE
	wildmon 6, 6, SPECIES_SHROOMISH
	wildmon 5, 5, SPECIES_TAILLOW
	wildmon 5, 5, SPECIES_SLAKOTH
	wildmon 6, 6, SPECIES_TAILLOW
	wildmon 6, 6, SPECIES_SLAKOTH

gPetalburgWoods_LandMonsInfo::
	wildmoninfo 20, gPetalburgWoods_LandMons
