@ MAP_ROUTE112
@ ROM 0x0852B7C4-0x0852B7FC

gRoute112_LandMons::
	wildmon 15, 15, SPECIES_NUMEL
	wildmon 15, 15, SPECIES_NUMEL
	wildmon 15, 15, SPECIES_MARILL
	wildmon 14, 14, SPECIES_NUMEL
	wildmon 14, 14, SPECIES_NUMEL
	wildmon 14, 14, SPECIES_MARILL
	wildmon 16, 16, SPECIES_NUMEL
	wildmon 16, 16, SPECIES_MARILL
	wildmon 16, 16, SPECIES_NUMEL
	wildmon 16, 16, SPECIES_NUMEL
	wildmon 16, 16, SPECIES_NUMEL
	wildmon 16, 16, SPECIES_NUMEL

gRoute112_LandMonsInfo::
	wildmoninfo 20, gRoute112_LandMons
