@ MAP_ROUTE105
@ ROM 0x0852B654-0x0852B6A0

gRoute105_WaterMons::
	wildmon 5, 35, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 25, 30, SPECIES_PELIPPER
	wildmon 25, 30, SPECIES_PELIPPER

gRoute105_WaterMonsInfo::
	wildmoninfo 4, gRoute105_WaterMons

gRoute105_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WAILMER
	wildmon 25, 30, SPECIES_WAILMER
	wildmon 30, 35, SPECIES_WAILMER
	wildmon 20, 25, SPECIES_WAILMER
	wildmon 35, 40, SPECIES_WAILMER
	wildmon 40, 45, SPECIES_WAILMER

gRoute105_FishingMonsInfo::
	wildmoninfo 30, gRoute105_FishingMons
