@ MAP_ROUTE116
@ ROM 0x0852B8D4-0x0852B90C

gRoute116_LandMons::
	wildmon 6, 6, SPECIES_POOCHYENA
	wildmon 6, 6, SPECIES_WHISMUR
	wildmon 6, 6, SPECIES_NINCADA
	wildmon 7, 7, SPECIES_ABRA
	wildmon 7, 7, SPECIES_NINCADA
	wildmon 6, 6, SPECIES_TAILLOW
	wildmon 7, 7, SPECIES_TAILLOW
	wildmon 8, 8, SPECIES_TAILLOW
	wildmon 7, 7, SPECIES_POOCHYENA
	wildmon 8, 8, SPECIES_POOCHYENA
	wildmon 7, 7, SPECIES_SKITTY
	wildmon 8, 8, SPECIES_SKITTY

gRoute116_LandMonsInfo::
	wildmoninfo 20, gRoute116_LandMons
