@ MAP_ROUTE110
@ ROM 0x0852B6A0-0x0852B724

gRoute110_LandMons::
	wildmon 12, 12, SPECIES_POOCHYENA
	wildmon 12, 12, SPECIES_ELECTRIKE
	wildmon 12, 12, SPECIES_GULPIN
	wildmon 13, 13, SPECIES_ELECTRIKE
	wildmon 13, 13, SPECIES_MINUN
	wildmon 13, 13, SPECIES_ODDISH
	wildmon 13, 13, SPECIES_MINUN
	wildmon 13, 13, SPECIES_GULPIN
	wildmon 12, 12, SPECIES_WINGULL
	wildmon 12, 12, SPECIES_WINGULL
	wildmon 12, 12, SPECIES_PLUSLE
	wildmon 13, 13, SPECIES_PLUSLE

gRoute110_LandMonsInfo::
	wildmoninfo 20, gRoute110_LandMons

gRoute110_WaterMons::
	wildmon 5, 35, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 25, 30, SPECIES_PELIPPER
	wildmon 25, 30, SPECIES_PELIPPER

gRoute110_WaterMonsInfo::
	wildmoninfo 4, gRoute110_WaterMons

gRoute110_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WAILMER
	wildmon 25, 30, SPECIES_WAILMER
	wildmon 30, 35, SPECIES_WAILMER
	wildmon 20, 25, SPECIES_WAILMER
	wildmon 35, 40, SPECIES_WAILMER
	wildmon 40, 45, SPECIES_WAILMER

gRoute110_FishingMonsInfo::
	wildmoninfo 30, gRoute110_FishingMons
