@ MAP_ROUTE124
@ ROM 0x0852BA14-0x0852BA60

gRoute124_WaterMons::
	wildmon 5, 35, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 25, 30, SPECIES_PELIPPER
	wildmon 25, 30, SPECIES_PELIPPER

gRoute124_WaterMonsInfo::
	wildmoninfo 4, gRoute124_WaterMons

gRoute124_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WAILMER
	wildmon 30, 35, SPECIES_SHARPEDO
	wildmon 30, 35, SPECIES_WAILMER
	wildmon 25, 30, SPECIES_WAILMER
	wildmon 35, 40, SPECIES_WAILMER
	wildmon 40, 45, SPECIES_WAILMER

gRoute124_FishingMonsInfo::
	wildmoninfo 30, gRoute124_FishingMons
