gRoute101_LandMons::
	wildmon 2, 2, SPECIES_WURMPLE
	wildmon 2, 2, SPECIES_POOCHYENA
	wildmon 2, 2, SPECIES_WURMPLE
	wildmon 3, 3, SPECIES_WURMPLE
	wildmon 3, 3, SPECIES_POOCHYENA
	wildmon 3, 3, SPECIES_POOCHYENA
	wildmon 3, 3, SPECIES_WURMPLE
	wildmon 3, 3, SPECIES_POOCHYENA
	wildmon 2, 2, SPECIES_ZIGZAGOON
	wildmon 2, 2, SPECIES_ZIGZAGOON
	wildmon 3, 3, SPECIES_ZIGZAGOON
	wildmon 3, 3, SPECIES_ZIGZAGOON

gRoute101_LandMonsInfo::
	wildmoninfo 20, gRoute101_LandMons
