@ MAP_ROUTE104
@ ROM 0x0852B5D0-0x0852B654

gRoute104_LandMons::
	wildmon 4, 4, SPECIES_POOCHYENA
	wildmon 4, 4, SPECIES_WURMPLE
	wildmon 5, 5, SPECIES_POOCHYENA
	wildmon 5, 5, SPECIES_MARILL
	wildmon 4, 4, SPECIES_MARILL
	wildmon 5, 5, SPECIES_POOCHYENA
	wildmon 4, 4, SPECIES_TAILLOW
	wildmon 5, 5, SPECIES_TAILLOW
	wildmon 4, 4, SPECIES_WINGULL
	wildmon 4, 4, SPECIES_WINGULL
	wildmon 3, 3, SPECIES_WINGULL
	wildmon 5, 5, SPECIES_WINGULL

gRoute104_LandMonsInfo::
	wildmoninfo 20, gRoute104_LandMons

gRoute104_WaterMons::
	wildmon 10, 30, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 25, 30, SPECIES_PELIPPER
	wildmon 25, 30, SPECIES_PELIPPER

gRoute104_WaterMonsInfo::
	wildmoninfo 4, gRoute104_WaterMons

gRoute104_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 25, 30, SPECIES_MAGIKARP
	wildmon 30, 35, SPECIES_MAGIKARP
	wildmon 20, 25, SPECIES_MAGIKARP
	wildmon 35, 40, SPECIES_MAGIKARP
	wildmon 40, 45, SPECIES_MAGIKARP

gRoute104_FishingMonsInfo::
	wildmoninfo 30, gRoute104_FishingMons
