@ MAP_ROUTE106
@ ROM 0x0852BD98-0x0852BDE4

gRoute106_WaterMons::
	wildmon 5, 35, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 25, 30, SPECIES_PELIPPER
	wildmon 25, 30, SPECIES_PELIPPER

gRoute106_WaterMonsInfo::
	wildmoninfo 4, gRoute106_WaterMons

gRoute106_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WAILMER
	wildmon 25, 30, SPECIES_WAILMER
	wildmon 30, 35, SPECIES_WAILMER
	wildmon 20, 25, SPECIES_WAILMER
	wildmon 35, 40, SPECIES_WAILMER
	wildmon 40, 45, SPECIES_WAILMER

gRoute106_FishingMonsInfo::
	wildmoninfo 30, gRoute106_FishingMons
