@ MAP_ROUTE125
@ ROM 0x0852C3A0-0x0852C3EC

gRoute125_WaterMons::
	wildmon 5, 35, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 25, 30, SPECIES_PELIPPER
	wildmon 25, 30, SPECIES_PELIPPER

gRoute125_WaterMonsInfo::
	wildmoninfo 4, gRoute125_WaterMons

gRoute125_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WAILMER
	wildmon 30, 35, SPECIES_SHARPEDO
	wildmon 30, 35, SPECIES_WAILMER
	wildmon 25, 30, SPECIES_WAILMER
	wildmon 35, 40, SPECIES_WAILMER
	wildmon 40, 45, SPECIES_WAILMER

gRoute125_FishingMonsInfo::
	wildmoninfo 30, gRoute125_FishingMons
