@ MAP_ROUTE102
@ ROM 0x0852B4C8-0x0852B54C

gRoute102_LandMons::
	wildmon 3, 3, SPECIES_POOCHYENA
	wildmon 3, 3, SPECIES_WURMPLE
	wildmon 4, 4, SPECIES_POOCHYENA
	wildmon 4, 4, SPECIES_WURMPLE
	wildmon 3, 3, SPECIES_LOTAD
	wildmon 4, 4, SPECIES_LOTAD
	wildmon 3, 3, SPECIES_ZIGZAGOON
	wildmon 3, 3, SPECIES_ZIGZAGOON
	wildmon 4, 4, SPECIES_ZIGZAGOON
	wildmon 4, 4, SPECIES_RALTS
	wildmon 4, 4, SPECIES_ZIGZAGOON
	wildmon 3, 3, SPECIES_SEEDOT

gRoute102_LandMonsInfo::
	wildmoninfo 20, gRoute102_LandMons

gRoute102_WaterMons::
	wildmon 20, 30, SPECIES_MARILL
	wildmon 10, 20, SPECIES_MARILL
	wildmon 30, 35, SPECIES_MARILL
	wildmon 5, 10, SPECIES_MARILL
	wildmon 20, 30, SPECIES_GOLDEEN

gRoute102_WaterMonsInfo::
	wildmoninfo 4, gRoute102_WaterMons

gRoute102_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_GOLDEEN
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_GOLDEEN
	wildmon 10, 30, SPECIES_CORPHISH
	wildmon 25, 30, SPECIES_CORPHISH
	wildmon 30, 35, SPECIES_CORPHISH
	wildmon 20, 25, SPECIES_CORPHISH
	wildmon 35, 40, SPECIES_CORPHISH
	wildmon 40, 45, SPECIES_CORPHISH

gRoute102_FishingMonsInfo::
	wildmoninfo 30, gRoute102_FishingMons
