@ MAP_ROUTE108
@ ROM 0x0852BE30-0x0852BE7C

gRoute108_WaterMons::
	wildmon 5, 35, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 25, 30, SPECIES_PELIPPER
	wildmon 25, 30, SPECIES_PELIPPER

gRoute108_WaterMonsInfo::
	wildmoninfo 4, gRoute108_WaterMons

gRoute108_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WAILMER
	wildmon 25, 30, SPECIES_WAILMER
	wildmon 30, 35, SPECIES_WAILMER
	wildmon 20, 25, SPECIES_WAILMER
	wildmon 35, 40, SPECIES_WAILMER
	wildmon 40, 45, SPECIES_WAILMER

gRoute108_FishingMonsInfo::
	wildmoninfo 30, gRoute108_FishingMons
