@ MAP_RUSTURF_TUNNEL
@ ROM 0x0852BA98-0x0852BAD0

gRusturfTunnel_LandMons::
	wildmon 6, 6, SPECIES_WHISMUR
	wildmon 7, 7, SPECIES_WHISMUR
	wildmon 6, 6, SPECIES_WHISMUR
	wildmon 6, 6, SPECIES_WHISMUR
	wildmon 7, 7, SPECIES_WHISMUR
	wildmon 7, 7, SPECIES_WHISMUR
	wildmon 5, 5, SPECIES_WHISMUR
	wildmon 8, 8, SPECIES_WHISMUR
	wildmon 5, 5, SPECIES_WHISMUR
	wildmon 8, 8, SPECIES_WHISMUR
	wildmon 5, 5, SPECIES_WHISMUR
	wildmon 8, 8, SPECIES_WHISMUR

gRusturfTunnel_LandMonsInfo::
	wildmoninfo 10, gRusturfTunnel_LandMons
