@ MAP_SAFARI_ZONE_SOUTHWEST
@ ROM 0x0852CB10-0x0852CB94

gSafariZone_Southwest_LandMons::
	wildmon 25, 25, SPECIES_ODDISH
	wildmon 27, 27, SPECIES_ODDISH
	wildmon 25, 25, SPECIES_GIRAFARIG
	wildmon 27, 27, SPECIES_GIRAFARIG
	wildmon 25, 25, SPECIES_NATU
	wildmon 27, 27, SPECIES_DODUO
	wildmon 25, 25, SPECIES_GLOOM
	wildmon 27, 27, SPECIES_WOBBUFFET
	wildmon 25, 25, SPECIES_PIKACHU
	wildmon 27, 27, SPECIES_WOBBUFFET
	wildmon 27, 27, SPECIES_PIKACHU
	wildmon 29, 29, SPECIES_WOBBUFFET

gSafariZone_Southwest_LandMonsInfo::
	wildmoninfo 25, gSafariZone_Southwest_LandMons

gSafariZone_Southwest_WaterMons::
	wildmon 20, 30, SPECIES_PSYDUCK
	wildmon 20, 30, SPECIES_PSYDUCK
	wildmon 30, 35, SPECIES_PSYDUCK
	wildmon 30, 35, SPECIES_PSYDUCK
	wildmon 30, 35, SPECIES_PSYDUCK

gSafariZone_Southwest_WaterMonsInfo::
	wildmoninfo 9, gSafariZone_Southwest_WaterMons

gSafariZone_Southwest_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_GOLDEEN
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 25, SPECIES_GOLDEEN
	wildmon 10, 30, SPECIES_GOLDEEN
	wildmon 25, 30, SPECIES_GOLDEEN
	wildmon 30, 35, SPECIES_GOLDEEN
	wildmon 30, 35, SPECIES_SEAKING
	wildmon 35, 40, SPECIES_SEAKING
	wildmon 25, 30, SPECIES_SEAKING

gSafariZone_Southwest_FishingMonsInfo::
	wildmoninfo 35, gSafariZone_Southwest_FishingMons
