@ MAP_SAFARI_ZONE_NORTH
@ ROM 0x0852CB94-0x0852CBE8

gSafariZone_North_LandMons::
	wildmon 27, 27, SPECIES_PHANPY
	wildmon 27, 27, SPECIES_ODDISH
	wildmon 29, 29, SPECIES_PHANPY
	wildmon 29, 29, SPECIES_ODDISH
	wildmon 27, 27, SPECIES_NATU
	wildmon 29, 29, SPECIES_GLOOM
	wildmon 31, 31, SPECIES_GLOOM
	wildmon 29, 29, SPECIES_NATU
	wildmon 29, 29, SPECIES_XATU
	wildmon 27, 27, SPECIES_HERACROSS
	wildmon 31, 31, SPECIES_XATU
	wildmon 29, 29, SPECIES_HERACROSS

gSafariZone_North_LandMonsInfo::
	wildmoninfo 25, gSafariZone_North_LandMons

gSafariZone_North_RockSmashMons::
	wildmon 10, 15, SPECIES_GEODUDE
	wildmon 5, 10, SPECIES_GEODUDE
	wildmon 15, 20, SPECIES_GEODUDE
	wildmon 20, 25, SPECIES_GEODUDE
	wildmon 25, 30, SPECIES_GEODUDE

gSafariZone_North_RockSmashMonsInfo::
	wildmoninfo 25, gSafariZone_North_RockSmashMons
