@ MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM
@ ROM 0x0852D278-0x0852D2B0

gShoalCave_LowTideIceRoom_LandMons::
	wildmon 26, 26, SPECIES_ZUBAT
	wildmon 26, 26, SPECIES_SPHEAL
	wildmon 28, 28, SPECIES_ZUBAT
	wildmon 28, 28, SPECIES_SPHEAL
	wildmon 30, 30, SPECIES_ZUBAT
	wildmon 30, 30, SPECIES_SPHEAL
	wildmon 26, 26, SPECIES_SNORUNT
	wildmon 32, 32, SPECIES_SPHEAL
	wildmon 30, 30, SPECIES_GOLBAT
	wildmon 28, 28, SPECIES_SNORUNT
	wildmon 32, 32, SPECIES_GOLBAT
	wildmon 30, 30, SPECIES_SNORUNT

gShoalCave_LowTideIceRoom_LandMonsInfo::
	wildmoninfo 10, gShoalCave_LowTideIceRoom_LandMons
