@ MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM
@ ROM 0x0852CFC4-0x0852D048

gShoalCave_LowTideEntranceRoom_LandMons::
	wildmon 26, 26, SPECIES_ZUBAT
	wildmon 26, 26, SPECIES_SPHEAL
	wildmon 28, 28, SPECIES_ZUBAT
	wildmon 28, 28, SPECIES_SPHEAL
	wildmon 30, 30, SPECIES_ZUBAT
	wildmon 30, 30, SPECIES_SPHEAL
	wildmon 32, 32, SPECIES_ZUBAT
	wildmon 32, 32, SPECIES_SPHEAL
	wildmon 32, 32, SPECIES_GOLBAT
	wildmon 32, 32, SPECIES_SPHEAL
	wildmon 32, 32, SPECIES_GOLBAT
	wildmon 32, 32, SPECIES_SPHEAL

gShoalCave_LowTideEntranceRoom_LandMonsInfo::
	wildmoninfo 10, gShoalCave_LowTideEntranceRoom_LandMons

gShoalCave_LowTideEntranceRoom_WaterMons::
	wildmon 5, 35, SPECIES_TENTACOOL
	wildmon 5, 35, SPECIES_ZUBAT
	wildmon 25, 30, SPECIES_SPHEAL
	wildmon 25, 30, SPECIES_SPHEAL
	wildmon 25, 35, SPECIES_SPHEAL

gShoalCave_LowTideEntranceRoom_WaterMonsInfo::
	wildmoninfo 4, gShoalCave_LowTideEntranceRoom_WaterMons

gShoalCave_LowTideEntranceRoom_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WAILMER
	wildmon 25, 30, SPECIES_WAILMER
	wildmon 30, 35, SPECIES_WAILMER
	wildmon 20, 25, SPECIES_WAILMER
	wildmon 35, 40, SPECIES_WAILMER
	wildmon 40, 45, SPECIES_WAILMER

gShoalCave_LowTideEntranceRoom_FishingMonsInfo::
	wildmoninfo 10, gShoalCave_LowTideEntranceRoom_FishingMons
