@ MAP_SLATEPORT_CITY
@ ROM 0x0852D0E0-0x0852D12C

gSlateportCity_WaterMons::
	wildmon 5, 35, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WINGULL
	wildmon 15, 25, SPECIES_WINGULL
	wildmon 25, 30, SPECIES_PELIPPER
	wildmon 25, 30, SPECIES_PELIPPER

gSlateportCity_WaterMonsInfo::
	wildmoninfo 4, gSlateportCity_WaterMons

gSlateportCity_FishingMons::
	wildmon 5, 10, SPECIES_MAGIKARP
	wildmon 5, 10, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_MAGIKARP
	wildmon 10, 30, SPECIES_TENTACOOL
	wildmon 10, 30, SPECIES_WAILMER
	wildmon 25, 30, SPECIES_WAILMER
	wildmon 30, 35, SPECIES_WAILMER
	wildmon 20, 25, SPECIES_WAILMER
	wildmon 35, 40, SPECIES_WAILMER
	wildmon 40, 45, SPECIES_WAILMER

gSlateportCity_FishingMonsInfo::
	wildmoninfo 10, gSlateportCity_FishingMons
