@ MAP_VICTORY_ROAD_B1F
@ ROM 0x0852CC6C-0x0852CCC0

gVictoryRoad_B1F_LandMons::
	wildmon 40, 40, SPECIES_GOLBAT
	wildmon 40, 40, SPECIES_HARIYAMA
	wildmon 40, 40, SPECIES_LAIRON
	wildmon 40, 40, SPECIES_LAIRON
	wildmon 38, 38, SPECIES_GOLBAT
	wildmon 38, 38, SPECIES_HARIYAMA
	wildmon 42, 42, SPECIES_GOLBAT
	wildmon 42, 42, SPECIES_HARIYAMA
	wildmon 42, 42, SPECIES_LAIRON
	wildmon 38, 38, SPECIES_MAWILE
	wildmon 42, 42, SPECIES_LAIRON
	wildmon 38, 38, SPECIES_MAWILE

gVictoryRoad_B1F_LandMonsInfo::
	wildmoninfo 10, gVictoryRoad_B1F_LandMons

gVictoryRoad_B1F_RockSmashMons::
	wildmon 30, 40, SPECIES_GRAVELER
	wildmon 30, 40, SPECIES_GEODUDE
	wildmon 35, 40, SPECIES_GRAVELER
	wildmon 35, 40, SPECIES_GRAVELER
	wildmon 35, 40, SPECIES_GRAVELER

gVictoryRoad_B1F_RockSmashMonsInfo::
	wildmoninfo 20, gVictoryRoad_B1F_RockSmashMons
