	@ src/field_specials.c:2531 field_specials_line_2531
	.globl gFieldSpecialsMenuText_Block02_Item00
gFieldSpecialsMenuText_Block02_Item00: @ 0x085CBFEF
	.string "  0てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item00) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item00 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item00) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item00)
	.endif

	@ src/field_specials.c:2532 field_specials_line_2532
	.globl gFieldSpecialsMenuText_Block02_Item01
gFieldSpecialsMenuText_Block02_Item01: @ 0x085CBFF5
	.string " 10てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item01) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item01 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item01) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item01)
	.endif

	@ src/field_specials.c:2533 field_specials_line_2533
	.globl gFieldSpecialsMenuText_Block02_Item02
gFieldSpecialsMenuText_Block02_Item02: @ 0x085CBFFB
	.string " 20てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item02) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item02 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item02) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item02)
	.endif

	@ src/field_specials.c:2534 field_specials_line_2534
	.globl gFieldSpecialsMenuText_Block02_Item03
gFieldSpecialsMenuText_Block02_Item03: @ 0x085CC001
	.string " 30てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item03) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item03 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item03) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item03)
	.endif

	@ src/field_specials.c:2535 field_specials_line_2535
	.globl gFieldSpecialsMenuText_Block02_Item04
gFieldSpecialsMenuText_Block02_Item04: @ 0x085CC007
	.string " 40てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item04) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item04 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item04) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item04)
	.endif

	@ src/field_specials.c:2536 field_specials_line_2536
	.globl gFieldSpecialsMenuText_Block02_Item05
gFieldSpecialsMenuText_Block02_Item05: @ 0x085CC00D
	.string " 50てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item05) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item05 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item05) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item05)
	.endif

	@ src/field_specials.c:2537 field_specials_line_2537
	.globl gFieldSpecialsMenuText_Block02_Item06
gFieldSpecialsMenuText_Block02_Item06: @ 0x085CC013
	.string " 60てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item06) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item06 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item06) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item06)
	.endif

	@ src/field_specials.c:2538 field_specials_line_2538
	.globl gFieldSpecialsMenuText_Block02_Item07
gFieldSpecialsMenuText_Block02_Item07: @ 0x085CC019
	.string " 70てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item07) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item07 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item07) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item07)
	.endif

	@ src/field_specials.c:2539 field_specials_line_2539
	.globl gFieldSpecialsMenuText_Block02_Item08
gFieldSpecialsMenuText_Block02_Item08: @ 0x085CC01F
	.string " 80てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item08) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item08 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item08) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item08)
	.endif

	@ src/field_specials.c:2540 field_specials_line_2540
	.globl gFieldSpecialsMenuText_Block02_Item09
gFieldSpecialsMenuText_Block02_Item09: @ 0x085CC025
	.string " 90てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item09) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item09 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item09) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item09)
	.endif

	@ src/field_specials.c:2541 field_specials_line_2541
	.globl gFieldSpecialsMenuText_Block02_Item10
gFieldSpecialsMenuText_Block02_Item10: @ 0x085CC02B
	.string "100てん{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item10) > 0x6
	.error "gFieldSpecialsMenuText_Block02_Item10 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item10) < 0x6
	.space 0x6 - (. - gFieldSpecialsMenuText_Block02_Item10)
	.endif

	@ src/field_specials.c:2542 field_specials_line_2542
	.globl gFieldSpecialsMenuText_Block02_Item11
gFieldSpecialsMenuText_Block02_Item11: @ 0x085CC031
	.string "  ？{EOS}"
	.if (. - gFieldSpecialsMenuText_Block02_Item11) > 0x4
	.error "gFieldSpecialsMenuText_Block02_Item11 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block02_Item11) < 0x4
	.space 0x4 - (. - gFieldSpecialsMenuText_Block02_Item11)
	.endif

	@ src/field_specials.c:2546 field_specials_line_2546
	.globl gFieldSpecialsMenuText_Block03_Item00
gFieldSpecialsMenuText_Block03_Item00: @ 0x085CC035
	.string "キッスポスター   16BP{EOS}"
	.if (. - gFieldSpecialsMenuText_Block03_Item00) > 0xf
	.error "gFieldSpecialsMenuText_Block03_Item00 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block03_Item00) < 0xf
	.space 0xf - (. - gFieldSpecialsMenuText_Block03_Item00)
	.endif

	@ src/field_specials.c:2547 field_specials_line_2547
	.globl gFieldSpecialsMenuText_Block03_Item01
gFieldSpecialsMenuText_Block03_Item01: @ 0x085CC044
	.string "キッスクッション  32BP{EOS}"
	.if (. - gFieldSpecialsMenuText_Block03_Item01) > 0xf
	.error "gFieldSpecialsMenuText_Block03_Item01 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block03_Item01) < 0xf
	.space 0xf - (. - gFieldSpecialsMenuText_Block03_Item01)
	.endif

	@ src/field_specials.c:2548 field_specials_line_2548
	.globl gFieldSpecialsMenuText_Block03_Item02
gFieldSpecialsMenuText_Block03_Item02: @ 0x085CC053
	.string "ムチュールドール  32BP{EOS}"
	.if (. - gFieldSpecialsMenuText_Block03_Item02) > 0xf
	.error "gFieldSpecialsMenuText_Block03_Item02 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block03_Item02) < 0xf
	.space 0xf - (. - gFieldSpecialsMenuText_Block03_Item02)
	.endif

	@ src/field_specials.c:2549 field_specials_line_2549
	.globl gFieldSpecialsMenuText_Block03_Item03
gFieldSpecialsMenuText_Block03_Item03: @ 0x085CC062
	.string "トゲピードール   48BP{EOS}"
	.if (. - gFieldSpecialsMenuText_Block03_Item03) > 0xf
	.error "gFieldSpecialsMenuText_Block03_Item03 may not grow beyond its original slot"
	.endif
	.if (. - gFieldSpecialsMenuText_Block03_Item03) < 0xf
	.space 0xf - (. - gFieldSpecialsMenuText_Block03_Item03)
	.endif

