	@ pret/pokeemerald-jp direct xref for 0x084DDE4C: event_object_movement.s: CreateReflectionEffectSprites; faraway_island.s: sub_081D4110; field_effect.s: FldEff_LavaridgeGymWarp, FldEff_NPCFlyOut, FldEff_PopOutOfAsh, sub_080B86F0, sub_080B8C1C; field_effect_helpers.s: CreateWarpArrowSpr...
	.globl gFieldEffectObjectTemplatePointers
gFieldEffectObjectTemplatePointers: @ 0x084DDE4C
	@ analyzed canonical ROM range 0x084DDE4C-0x084E18FF
