	@ pret/pokeemerald-jp direct xref for 0x08572F6C: water.s: sub_08109010
	.globl gBattleAnimSpriteTemplate_WaterHit
gBattleAnimSpriteTemplate_WaterHit: @ 0x08572F6C
	@ analyzed canonical ROM range 0x08572F6C-0x08572FCB
	@ pointer/nullable table
	.4byte 0x27A427A4 @ +0x0
	.4byte gOamData_AffineNormal_ObjBlend_32x32 @ +0x4
	.4byte gDummySpriteAnimTable @ +0x8
	.4byte 0 @ +0xC
	.4byte sAffineAnims_HitSplat @ +0x10
	.4byte sub_08116BD8 @ +0x14
	.globl gBattleAnimSpriteTemplate_WaterHitRandomOffset
gBattleAnimSpriteTemplate_WaterHitRandomOffset: @ 0x08572F84
	.4byte 0x27972797 @ +0x18
	.4byte gOamData_AffineNormal_ObjBlend_32x32 @ +0x1C
	.4byte gDummySpriteAnimTable @ +0x20
	.4byte 0 @ +0x24
	.4byte sAffineAnims_HitSplat @ +0x28
	.4byte sub_08116CA8 @ +0x2C
	.globl gBattleAnimSpriteTemplate_WaterHitOnBattler
gBattleAnimSpriteTemplate_WaterHitOnBattler: @ 0x08572F9C
	.4byte 0x27972797 @ +0x30
	.4byte gOamData_AffineNormal_ObjBlend_32x32 @ +0x34
	.4byte gDummySpriteAnimTable @ +0x38
	.4byte 0 @ +0x3C
	.4byte sAffineAnims_HitSplat @ +0x40
	.4byte sub_08116D40 @ +0x44
	.4byte 0x282D282D @ +0x48
	.4byte gOamData_AffineOff_ObjBlend_32x32 @ +0x4C
	.4byte gDummySpriteAnimTable @ +0x50
	.4byte 0 @ +0x54
	.4byte gDummySpriteAffineAnimTable @ +0x58
	.4byte sub_08116DB0 @ +0x5C
