	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5E8242
gText_Rom_5E8242: @ 0x085E8242
	.string "こうげき$"
	.if (. - gText_Rom_5E8242) > 0x5
	.error "gText_Rom_5E8242 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5E8242) < 0x5
	.space 0x5 - (. - gText_Rom_5E8242)
	.endif
	.incbin "baserom.gba", 0x5e8247, 0x33

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5E827A
gText_Rom_5E827A: @ 0x085E827A
	.string "こうげき$"
	.if (. - gText_Rom_5E827A) > 0x5
	.error "gText_Rom_5E827A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5E827A) < 0x5
	.space 0x5 - (. - gText_Rom_5E827A)
	.endif
	.incbin "baserom.gba", 0x5e827f, 0x74

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5E82F3
gText_Rom_5E82F3: @ 0x085E82F3
	.string "こうげき$"
	.if (. - gText_Rom_5E82F3) > 0x5
	.error "gText_Rom_5E82F3 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5E82F3) < 0x5
	.space 0x5 - (. - gText_Rom_5E82F3)
	.endif
	.incbin "baserom.gba", 0x5e82f8, 0x2e

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5E8326
gText_Rom_5E8326: @ 0x085E8326
	.string "あげる$"
	.if (. - gText_Rom_5E8326) > 0x4
	.error "gText_Rom_5E8326 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5E8326) < 0x4
	.space 0x4 - (. - gText_Rom_5E8326)
	.endif
	.incbin "baserom.gba", 0x5e832a, 0x37

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5E8361
gText_Rom_5E8361: @ 0x085E8361
	.string "こうげき$"
	.if (. - gText_Rom_5E8361) > 0x5
	.error "gText_Rom_5E8361 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5E8361) < 0x5
	.space 0x5 - (. - gText_Rom_5E8361)
	.endif
	.incbin "baserom.gba", 0x5e8366, 0x32

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5E8398
gText_Rom_5E8398: @ 0x085E8398
	.string "こうげき$"
	.if (. - gText_Rom_5E8398) > 0x5
	.error "gText_Rom_5E8398 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5E8398) < 0x5
	.space 0x5 - (. - gText_Rom_5E8398)
	.endif
	.incbin "baserom.gba", 0x5e839d, 0x6d

	@ src/strings.c:1046 gText_Exit3 (+1 aliases)
	.globl gText_Rom_5E840A
gText_Rom_5E840A: @ 0x085E840A
	.string "おわる$"
	.if (. - gText_Rom_5E840A) > 0x4
	.error "gText_Rom_5E840A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5E840A) < 0x4
	.space 0x4 - (. - gText_Rom_5E840A)
	.endif
	.incbin "baserom.gba", 0x5e840e, 0x33

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5E8441
gText_Rom_5E8441: @ 0x085E8441
	.string "こうげき$"
	.if (. - gText_Rom_5E8441) > 0x5
	.error "gText_Rom_5E8441 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5E8441) < 0x5
	.space 0x5 - (. - gText_Rom_5E8441)
	.endif
	.incbin "baserom.gba", 0x5e8446, 0x36

