	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5EBFBF
gText_Rom_5EBFBF: @ 0x085EBFBF
	.string "こうげき$"
	.if (. - gText_Rom_5EBFBF) > 0x5
	.error "gText_Rom_5EBFBF may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBFBF) < 0x5
	.space 0x5 - (. - gText_Rom_5EBFBF)
	.endif
	.incbin "baserom.gba", 0x5ebfc4, 0x2d

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5EBFF1
gText_Rom_5EBFF1: @ 0x085EBFF1
	.string "こうげき$"
	.if (. - gText_Rom_5EBFF1) > 0x5
	.error "gText_Rom_5EBFF1 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBFF1) < 0x5
	.space 0x5 - (. - gText_Rom_5EBFF1)
	.endif
	.incbin "baserom.gba", 0x5ebff6, 0x6d

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5EC063
gText_Rom_5EC063: @ 0x085EC063
	.string "あげる$"
	.if (. - gText_Rom_5EC063) > 0x4
	.error "gText_Rom_5EC063 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC063) < 0x4
	.space 0x4 - (. - gText_Rom_5EC063)
	.endif
	.incbin "baserom.gba", 0x5ec067, 0x2dd

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EC344
gText_Rom_5EC344: @ 0x085EC344
	.string "しまう$"
	.if (. - gText_Rom_5EC344) > 0x4
	.error "gText_Rom_5EC344 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC344) < 0x4
	.space 0x4 - (. - gText_Rom_5EC344)
	.endif
	.incbin "baserom.gba", 0x5ec348, 0x34

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EC37C
gText_Rom_5EC37C: @ 0x085EC37C
	.string "しまう$"
	.if (. - gText_Rom_5EC37C) > 0x4
	.error "gText_Rom_5EC37C may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC37C) < 0x4
	.space 0x4 - (. - gText_Rom_5EC37C)
	.endif
	.incbin "baserom.gba", 0x5ec380, 0x184

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EC504
gText_Rom_5EC504: @ 0x085EC504
	.string "しまう$"
	.if (. - gText_Rom_5EC504) > 0x4
	.error "gText_Rom_5EC504 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC504) < 0x4
	.space 0x4 - (. - gText_Rom_5EC504)
	.endif
	.incbin "baserom.gba", 0x5ec508, 0x17c

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5EC684
gText_Rom_5EC684: @ 0x085EC684
	.string "あげる$"
	.if (. - gText_Rom_5EC684) > 0x4
	.error "gText_Rom_5EC684 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC684) < 0x4
	.space 0x4 - (. - gText_Rom_5EC684)
	.endif
	.incbin "baserom.gba", 0x5ec688, 0xaa

	@ src/data/easy_chat/easy_chat_group_actions.h:448 easy_chat_group_actions_line_448
	.globl gText_Rom_5EC732
gText_Rom_5EC732: @ 0x085EC732
	.string "られない$"
	.if (. - gText_Rom_5EC732) > 0x5
	.error "gText_Rom_5EC732 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC732) < 0x5
	.space 0x5 - (. - gText_Rom_5EC732)
	.endif
	.incbin "baserom.gba", 0x5ec737, 0x69

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5EC7A0
gText_Rom_5EC7A0: @ 0x085EC7A0
	.string "こうげき$"
	.if (. - gText_Rom_5EC7A0) > 0x5
	.error "gText_Rom_5EC7A0 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC7A0) < 0x5
	.space 0x5 - (. - gText_Rom_5EC7A0)
	.endif
	.incbin "baserom.gba", 0x5ec7a5, 0xda

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5EC87F
gText_Rom_5EC87F: @ 0x085EC87F
	.string "こうげき$"
	.if (. - gText_Rom_5EC87F) > 0x5
	.error "gText_Rom_5EC87F may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC87F) < 0x5
	.space 0x5 - (. - gText_Rom_5EC87F)
	.endif
	.incbin "baserom.gba", 0x5ec884, 0x31

	@ src/data/easy_chat/easy_chat_group_actions.h:448 easy_chat_group_actions_line_448
	.globl gText_Rom_5EC8B5
gText_Rom_5EC8B5: @ 0x085EC8B5
	.string "られない$"
	.if (. - gText_Rom_5EC8B5) > 0x5
	.error "gText_Rom_5EC8B5 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC8B5) < 0x5
	.space 0x5 - (. - gText_Rom_5EC8B5)
	.endif
	.incbin "baserom.gba", 0x5ec8ba, 0x36

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5EC8F0
gText_Rom_5EC8F0: @ 0x085EC8F0
	.string "こうげき$"
	.if (. - gText_Rom_5EC8F0) > 0x5
	.error "gText_Rom_5EC8F0 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC8F0) < 0x5
	.space 0x5 - (. - gText_Rom_5EC8F0)
	.endif
	.incbin "baserom.gba", 0x5ec8f5, 0x33

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5EC928
gText_Rom_5EC928: @ 0x085EC928
	.string "あげる$"
	.if (. - gText_Rom_5EC928) > 0x4
	.error "gText_Rom_5EC928 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC928) < 0x4
	.space 0x4 - (. - gText_Rom_5EC928)
	.endif
	.incbin "baserom.gba", 0x5ec92c, 0x30

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EC95C
gText_Rom_5EC95C: @ 0x085EC95C
	.string "しまう$"
	.if (. - gText_Rom_5EC95C) > 0x4
	.error "gText_Rom_5EC95C may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC95C) < 0x4
	.space 0x4 - (. - gText_Rom_5EC95C)
	.endif
	.incbin "baserom.gba", 0x5ec960, 0x33

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5EC993
gText_Rom_5EC993: @ 0x085EC993
	.string "あげる$"
	.if (. - gText_Rom_5EC993) > 0x4
	.error "gText_Rom_5EC993 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC993) < 0x4
	.space 0x4 - (. - gText_Rom_5EC993)
	.endif
	.incbin "baserom.gba", 0x5ec997, 0x33

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5EC9CA
gText_Rom_5EC9CA: @ 0x085EC9CA
	.string "こうげき$"
	.if (. - gText_Rom_5EC9CA) > 0x5
	.error "gText_Rom_5EC9CA may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EC9CA) < 0x5
	.space 0x5 - (. - gText_Rom_5EC9CA)
	.endif
	.incbin "baserom.gba", 0x5ec9cf, 0x3d

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5ECA0C
gText_Rom_5ECA0C: @ 0x085ECA0C
	.string "しまう$"
	.if (. - gText_Rom_5ECA0C) > 0x4
	.error "gText_Rom_5ECA0C may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5ECA0C) < 0x4
	.space 0x4 - (. - gText_Rom_5ECA0C)
	.endif
	.incbin "baserom.gba", 0x5eca10, 0x2a

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5ECA3A
gText_Rom_5ECA3A: @ 0x085ECA3A
	.string "あげる$"
	.if (. - gText_Rom_5ECA3A) > 0x4
	.error "gText_Rom_5ECA3A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5ECA3A) < 0x4
	.space 0x4 - (. - gText_Rom_5ECA3A)
	.endif
	.incbin "baserom.gba", 0x5eca3e, 0x152

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5ECB90
gText_Rom_5ECB90: @ 0x085ECB90
	.string "こうげき$"
	.if (. - gText_Rom_5ECB90) > 0x5
	.error "gText_Rom_5ECB90 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5ECB90) < 0x5
	.space 0x5 - (. - gText_Rom_5ECB90)
	.endif
	.incbin "baserom.gba", 0x5ecb95, 0x6c

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5ECC01
gText_Rom_5ECC01: @ 0x085ECC01
	.string "あげる$"
	.if (. - gText_Rom_5ECC01) > 0x4
	.error "gText_Rom_5ECC01 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5ECC01) < 0x4
	.space 0x4 - (. - gText_Rom_5ECC01)
	.endif
	.incbin "baserom.gba", 0x5ecc05, 0x6a

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5ECC6F
gText_Rom_5ECC6F: @ 0x085ECC6F
	.string "あげる$"
	.if (. - gText_Rom_5ECC6F) > 0x4
	.error "gText_Rom_5ECC6F may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5ECC6F) < 0x4
	.space 0x4 - (. - gText_Rom_5ECC6F)
	.endif
	.incbin "baserom.gba", 0x5ecc73, 0x34

	@ src/battle_debug.c:337 battle_debug_line_337 (+5 aliases)
	.globl gText_Rom_5ECCA7
gText_Rom_5ECCA7: @ 0x085ECCA7
	.string "こうげき$"
	.if (. - gText_Rom_5ECCA7) > 0x5
	.error "gText_Rom_5ECCA7 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5ECCA7) < 0x5
	.space 0x5 - (. - gText_Rom_5ECCA7)
	.endif
	.incbin "baserom.gba", 0x5eccac, 0x34

	@ src/data/easy_chat/easy_chat_group_actions.h:448 easy_chat_group_actions_line_448
	.globl gText_Rom_5ECCE0
gText_Rom_5ECCE0: @ 0x085ECCE0
	.string "られない$"
	.if (. - gText_Rom_5ECCE0) > 0x5
	.error "gText_Rom_5ECCE0 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5ECCE0) < 0x5
	.space 0x5 - (. - gText_Rom_5ECCE0)
	.endif
	.incbin "baserom.gba", 0x5ecce5, 0xa7

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5ECD8C
gText_Rom_5ECD8C: @ 0x085ECD8C
	.string "しまう$"
	.if (. - gText_Rom_5ECD8C) > 0x4
	.error "gText_Rom_5ECD8C may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5ECD8C) < 0x4
	.space 0x4 - (. - gText_Rom_5ECD8C)
	.endif
	.incbin "baserom.gba", 0x5ecd90, 0x14

