	.globl gUnknown_82EC600
gUnknown_82EC600: @ 0x082EC600
	.incbin "baserom.gba", 0x2ec600, 0x38
	.globl gUnknown_82EC638
gUnknown_82EC638: @ 0x082EC638
	.incbin "baserom.gba", 0x2ec638, 0x2c
	.globl gUnknown_82EC664
gUnknown_82EC664: @ 0x082EC664
	.incbin "baserom.gba", 0x2ec664, 0xf
	.globl gUnknown_82EC673
gUnknown_82EC673: @ 0x082EC673
	.incbin "baserom.gba", 0x2ec673, 0x4
	.globl gUnknown_82EC677
gUnknown_82EC677: @ 0x082EC677
	.incbin "baserom.gba", 0x2ec677, 0x5
	.globl gUnknown_82EC67C
gUnknown_82EC67C: @ 0x082EC67C
	.incbin "baserom.gba", 0x2ec67c, 0x18
	.globl gUnknown_82EC694
gUnknown_82EC694: @ 0x082EC694
	.incbin "baserom.gba", 0x2ec694, 0x3e4
	.globl gUnknown_82ECA78
gUnknown_82ECA78: @ 0x082ECA78
	.incbin "baserom.gba", 0x2eca78, 0x34
	.globl gUnknown_82ECAAC
gUnknown_82ECAAC: @ 0x082ECAAC
	.incbin "baserom.gba", 0x2ecaac, 0xc
	.globl gUnknown_82ECAB8
gUnknown_82ECAB8: @ 0x082ECAB8
	.incbin "baserom.gba", 0x2ecab8, 0xf0
	.globl gUnknown_82ECBA8
gUnknown_82ECBA8: @ 0x082ECBA8
	.incbin "baserom.gba", 0x2ecba8, 0xa4
	.globl gUnknown_82ECC4C
gUnknown_82ECC4C: @ 0x082ECC4C
	.incbin "baserom.gba", 0x2ecc4c, 0x20
	.globl gUnknown_82ECC6C
gUnknown_82ECC6C: @ 0x082ECC6C
	.incbin "baserom.gba", 0x2ecc6c, 0xd8
	.globl gUnknown_82ECD44
gUnknown_82ECD44: @ 0x082ECD44
	.incbin "baserom.gba", 0x2ecd44, 0x18
	.globl gUnknown_82ECD5C
gUnknown_82ECD5C: @ 0x082ECD5C
	.incbin "baserom.gba", 0x2ecd5c, 0x8
	.globl gUnknown_82ECD64
gUnknown_82ECD64: @ 0x082ECD64
	.incbin "baserom.gba", 0x2ecd64, 0x28
	.globl gUnknown_82ECD8C
gUnknown_82ECD8C: @ 0x082ECD8C
	.incbin "baserom.gba", 0x2ecd8c, 0xc
	.globl gUnknown_82ECD98
gUnknown_82ECD98: @ 0x082ECD98
	.incbin "baserom.gba", 0x2ecd98, 0x14
	.globl gUnknown_82ECDAC
gUnknown_82ECDAC: @ 0x082ECDAC
	.incbin "baserom.gba", 0x2ecdac, 0x18
	.globl gUnknown_82ECDC4
gUnknown_82ECDC4: @ 0x082ECDC4
	.incbin "baserom.gba", 0x2ecdc4, 0x24
	.globl gUnknown_82ECDE8
gUnknown_82ECDE8: @ 0x082ECDE8
	.incbin "baserom.gba", 0x2ecde8, 0x16
	.globl gUnknown_82ECDFE
gUnknown_82ECDFE: @ 0x082ECDFE
	.incbin "baserom.gba", 0x2ecdfe, 0x9
	.globl gUnknown_82ECE07
gUnknown_82ECE07: @ 0x082ECE07
	.incbin "baserom.gba", 0x2ece07, 0xa
	.globl gUnknown_82ECE11
gUnknown_82ECE11: @ 0x082ECE11
	.incbin "baserom.gba", 0x2ece11, 0x7
	.globl gUnknown_82ECE18
gUnknown_82ECE18: @ 0x082ECE18
	.incbin "baserom.gba", 0x2ece18, 0x64
	.globl gUnknown_82ECE7C
gUnknown_82ECE7C: @ 0x082ECE7C
	.incbin "baserom.gba", 0x2ece7c, 0x20
	.globl gUnknown_82ECE9C
gUnknown_82ECE9C: @ 0x082ECE9C
	.incbin "baserom.gba", 0x2ece9c, 0xe4
	.globl gUnknown_82ECF80
gUnknown_82ECF80: @ 0x082ECF80
	.incbin "baserom.gba", 0x2ecf80, 0xc
	.globl gUnknown_82ECF8C
gUnknown_82ECF8C: @ 0x082ECF8C
	.incbin "baserom.gba", 0x2ecf8c, 0x1c
	.globl gUnknown_82ECFA8
gUnknown_82ECFA8: @ 0x082ECFA8
	.incbin "baserom.gba", 0x2ecfa8, 0x8
	.globl gUnknown_82ECFB0
gUnknown_82ECFB0: @ 0x082ECFB0
	.incbin "baserom.gba", 0x2ecfb0, 0x60
	.globl gUnknown_82ED010
gUnknown_82ED010: @ 0x082ED010
	.incbin "baserom.gba", 0x2ed010, 0x18
	.globl gUnknown_82ED028
gUnknown_82ED028: @ 0x082ED028
	.incbin "baserom.gba", 0x2ed028, 0x10
	.globl gUnknown_82ED038
gUnknown_82ED038: @ 0x082ED038
	.incbin "baserom.gba", 0x2ed038, 0x18
	.globl gUnknown_82ED050
gUnknown_82ED050: @ 0x082ED050
	.incbin "baserom.gba", 0x2ed050, 0xec
	.globl gUnknown_82ED13C
gUnknown_82ED13C: @ 0x082ED13C
	.incbin "baserom.gba", 0x2ed13c, 0xe4
