	@ pret/pokeemerald-jp direct xref for 0x0853738A: scanline_effect.s: Sound_DrawChoices
	.globl gScanlineEffectData_0853738A
gScanlineEffectData_0853738A: @ 0x0853738A
	@ analyzed canonical ROM range 0x0853738A-0x08537392
	@ structured u8 payload; no safe higher-level semantic type was provable
	@ ANALYSIS: U8_DATA size=0x9 bytes=9
	.byte 0xFC, 0x01, 0x06, 0xFC, 0x03, 0x07, 0x20, 0x29, 0xFF
	@ pret/pokeemerald-jp direct xref for 0x08537393: scanline_effect.s: Sound_DrawChoices
	.globl gScanlineEffectData_08537393
gScanlineEffectData_08537393: @ 0x08537393
	@ analyzed canonical ROM range 0x08537393-0x0853739C
	@ structured u8 payload; no safe higher-level semantic type was provable
	@ ANALYSIS: U8_DATA size=0xA bytes=10
	.byte 0xFC, 0x01, 0x06, 0xFC, 0x03, 0x07, 0x20, 0x15, 0x02, 0xFF

