	@ src/data/easy_chat/easy_chat_group_adjectives.h:100 easy_chat_group_adjectives_line_100
	.globl gText_Rom_578206
gText_Rom_578206: @ 0x08578206
	.string "どんどん{EOS}"
	.if (. - gText_Rom_578206) > 0x5
	.error "gText_Rom_578206 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578206) < 0x5
	.space 0x5 - (. - gText_Rom_578206)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:106 easy_chat_group_adjectives_line_106
	.globl gText_Rom_57820B
gText_Rom_57820B: @ 0x0857820B
	.string "なでなで{EOS}"
	.if (. - gText_Rom_57820B) > 0x5
	.error "gText_Rom_57820B may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57820B) < 0x5
	.space 0x5 - (. - gText_Rom_57820B)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:112 easy_chat_group_adjectives_line_112
	.globl gText_Rom_578210
gText_Rom_578210: @ 0x08578210
	.string "ぬるぬる{EOS}"
	.if (. - gText_Rom_578210) > 0x5
	.error "gText_Rom_578210 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578210) < 0x5
	.space 0x5 - (. - gText_Rom_578210)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:118 easy_chat_group_adjectives_line_118
	.globl gText_Rom_578215
gText_Rom_578215: @ 0x08578215
	.string "はあはあ{EOS}"
	.if (. - gText_Rom_578215) > 0x5
	.error "gText_Rom_578215 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578215) < 0x5
	.space 0x5 - (. - gText_Rom_578215)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:124 easy_chat_group_adjectives_line_124
	.globl gText_Rom_57821A
gText_Rom_57821A: @ 0x0857821A
	.string "バキバキ{EOS}"
	.if (. - gText_Rom_57821A) > 0x5
	.error "gText_Rom_57821A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57821A) < 0x5
	.space 0x5 - (. - gText_Rom_57821A)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:130 easy_chat_group_adjectives_line_130
	.globl gText_Rom_57821F
gText_Rom_57821F: @ 0x0857821F
	.string "ぱくぱく{EOS}"
	.if (. - gText_Rom_57821F) > 0x5
	.error "gText_Rom_57821F may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57821F) < 0x5
	.space 0x5 - (. - gText_Rom_57821F)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:136 easy_chat_group_adjectives_line_136
	.globl gText_Rom_578224
gText_Rom_578224: @ 0x08578224
	.string "パラパラ{EOS}"
	.if (. - gText_Rom_578224) > 0x5
	.error "gText_Rom_578224 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578224) < 0x5
	.space 0x5 - (. - gText_Rom_578224)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:142 easy_chat_group_adjectives_line_142
	.globl gText_Rom_578229
gText_Rom_578229: @ 0x08578229
	.string "バリバリ{EOS}"
	.if (. - gText_Rom_578229) > 0x5
	.error "gText_Rom_578229 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578229) < 0x5
	.space 0x5 - (. - gText_Rom_578229)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:148 easy_chat_group_adjectives_line_148
	.globl gText_Rom_57822E
gText_Rom_57822E: @ 0x0857822E
	.string "ふにゃふにゃ{EOS}"
	.if (. - gText_Rom_57822E) > 0x7
	.error "gText_Rom_57822E may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57822E) < 0x7
	.space 0x7 - (. - gText_Rom_57822E)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:154 easy_chat_group_adjectives_line_154
	.globl gText_Rom_578235
gText_Rom_578235: @ 0x08578235
	.string "ふらふら{EOS}"
	.if (. - gText_Rom_578235) > 0x5
	.error "gText_Rom_578235 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578235) < 0x5
	.space 0x5 - (. - gText_Rom_578235)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:160 easy_chat_group_adjectives_line_160
	.globl gText_Rom_57823A
gText_Rom_57823A: @ 0x0857823A
	.string "ブルブル{EOS}"
	.if (. - gText_Rom_57823A) > 0x5
	.error "gText_Rom_57823A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57823A) < 0x5
	.space 0x5 - (. - gText_Rom_57823A)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:166 easy_chat_group_adjectives_line_166
	.globl gText_Rom_57823F
gText_Rom_57823F: @ 0x0857823F
	.string "べろべろ{EOS}"
	.if (. - gText_Rom_57823F) > 0x5
	.error "gText_Rom_57823F may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57823F) < 0x5
	.space 0x5 - (. - gText_Rom_57823F)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:172 easy_chat_group_adjectives_line_172
	.globl gText_Rom_578244
gText_Rom_578244: @ 0x08578244
	.string "ボロボロ{EOS}"
	.if (. - gText_Rom_578244) > 0x5
	.error "gText_Rom_578244 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578244) < 0x5
	.space 0x5 - (. - gText_Rom_578244)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:178 easy_chat_group_adjectives_line_178
	.globl gText_Rom_578249
gText_Rom_578249: @ 0x08578249
	.string "ますます{EOS}"
	.if (. - gText_Rom_578249) > 0x5
	.error "gText_Rom_578249 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578249) < 0x5
	.space 0x5 - (. - gText_Rom_578249)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:184 easy_chat_group_adjectives_line_184
	.globl gText_Rom_57824E
gText_Rom_57824E: @ 0x0857824E
	.string "まだまだ{EOS}"
	.if (. - gText_Rom_57824E) > 0x5
	.error "gText_Rom_57824E may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57824E) < 0x5
	.space 0x5 - (. - gText_Rom_57824E)
	.endif

	@ src/data/easy_chat/easy_chat_group_adjectives.h:190 easy_chat_group_adjectives_line_190
	.globl gText_Rom_578253
gText_Rom_578253: @ 0x08578253
	.string "めちゃめちゃ{EOS}"
	.if (. - gText_Rom_578253) > 0x7
	.error "gText_Rom_578253 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_578253) < 0x7
	.space 0x7 - (. - gText_Rom_578253)
	.endif

