	@ src/data/moves_info.h:6328 moves_info_line_6328
	.globl gText_Rom_5EB79C
gText_Rom_5EB79C: @ 0x085EB79C
	.string "たくわえる$"
	.if (. - gText_Rom_5EB79C) > 0x6
	.error "gText_Rom_5EB79C may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EB79C) < 0x6
	.space 0x6 - (. - gText_Rom_5EB79C)
	.endif
	.incbin "baserom.gba", 0x5eb7a2, 0x155

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EB8F7
gText_Rom_5EB8F7: @ 0x085EB8F7
	.string "しまう$"
	.if (. - gText_Rom_5EB8F7) > 0x4
	.error "gText_Rom_5EB8F7 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EB8F7) < 0x4
	.space 0x4 - (. - gText_Rom_5EB8F7)
	.endif
	.incbin "baserom.gba", 0x5eb8fb, 0x1c1

	@ src/data/easy_chat/easy_chat_group_actions.h:16 easy_chat_group_actions_line_16 (+1 aliases)
	.globl gText_Rom_5EBABC
gText_Rom_5EBABC: @ 0x085EBABC
	.string "あげる$"
	.if (. - gText_Rom_5EBABC) > 0x4
	.error "gText_Rom_5EBABC may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBABC) < 0x4
	.space 0x4 - (. - gText_Rom_5EBABC)
	.endif
	.incbin "baserom.gba", 0x5ebac0, 0x9b

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EBB5B
gText_Rom_5EBB5B: @ 0x085EBB5B
	.string "しまう$"
	.if (. - gText_Rom_5EBB5B) > 0x4
	.error "gText_Rom_5EBB5B may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBB5B) < 0x4
	.space 0x4 - (. - gText_Rom_5EBB5B)
	.endif
	.incbin "baserom.gba", 0x5ebb5f, 0x153

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EBCB2
gText_Rom_5EBCB2: @ 0x085EBCB2
	.string "しまう$"
	.if (. - gText_Rom_5EBCB2) > 0x4
	.error "gText_Rom_5EBCB2 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBCB2) < 0x4
	.space 0x4 - (. - gText_Rom_5EBCB2)
	.endif
	.incbin "baserom.gba", 0x5ebcb6, 0x35

	@ src/data/easy_chat/easy_chat_group_actions.h:280 easy_chat_group_actions_line_280
	.globl gText_Rom_5EBCEB
gText_Rom_5EBCEB: @ 0x085EBCEB
	.string "できる$"
	.if (. - gText_Rom_5EBCEB) > 0x4
	.error "gText_Rom_5EBCEB may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBCEB) < 0x4
	.space 0x4 - (. - gText_Rom_5EBCEB)
	.endif
	.incbin "baserom.gba", 0x5ebcef, 0x17b

	@ src/data/easy_chat/easy_chat_group_actions.h:280 easy_chat_group_actions_line_280
	.globl gText_Rom_5EBE6A
gText_Rom_5EBE6A: @ 0x085EBE6A
	.string "できる$"
	.if (. - gText_Rom_5EBE6A) > 0x4
	.error "gText_Rom_5EBE6A may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBE6A) < 0x4
	.space 0x4 - (. - gText_Rom_5EBE6A)
	.endif
	.incbin "baserom.gba", 0x5ebe6e, 0x6b

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EBED9
gText_Rom_5EBED9: @ 0x085EBED9
	.string "しまう$"
	.if (. - gText_Rom_5EBED9) > 0x4
	.error "gText_Rom_5EBED9 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBED9) < 0x4
	.space 0x4 - (. - gText_Rom_5EBED9)
	.endif
	.incbin "baserom.gba", 0x5ebedd, 0x76

	@ src/data/easy_chat/easy_chat_group_actions.h:214 easy_chat_group_actions_line_214
	.globl gText_Rom_5EBF53
gText_Rom_5EBF53: @ 0x085EBF53
	.string "しまう$"
	.if (. - gText_Rom_5EBF53) > 0x4
	.error "gText_Rom_5EBF53 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBF53) < 0x4
	.space 0x4 - (. - gText_Rom_5EBF53)
	.endif
	.incbin "baserom.gba", 0x5ebf57, 0x34

	@ src/data/easy_chat/easy_chat_group_conditions.h:250 easy_chat_group_conditions_line_250
	.globl gText_Rom_5EBF8B
gText_Rom_5EBF8B: @ 0x085EBF8B
	.string "ちがう$"
	.if (. - gText_Rom_5EBF8B) > 0x4
	.error "gText_Rom_5EBF8B may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5EBF8B) < 0x4
	.space 0x4 - (. - gText_Rom_5EBF8B)
	.endif
	.incbin "baserom.gba", 0x5ebf8f, 0x30

