	.incbin "baserom.gba", 0x2eb7dc, 0x4c
	.globl gUnknown_82EB828
gUnknown_82EB828: @ 0x082EB828
	.incbin "baserom.gba", 0x2eb828, 0x18
	.globl gUnknown_82EB840
gUnknown_82EB840: @ 0x082EB840
	.incbin "baserom.gba", 0x2eb840, 0x18
	.globl gUnknown_82EB858
gUnknown_82EB858: @ 0x082EB858
	.incbin "baserom.gba", 0x2eb858, 0x8
	.globl gUnknown_82EB860
gUnknown_82EB860: @ 0x082EB860
	.incbin "baserom.gba", 0x2eb860, 0x198
	.globl gUnknown_82EB9F8
gUnknown_82EB9F8: @ 0x082EB9F8
	.incbin "baserom.gba", 0x2eb9f8, 0x8
	.globl gUnknown_82EBA00
gUnknown_82EBA00: @ 0x082EBA00
	.incbin "baserom.gba", 0x2eba00, 0xc8
	.globl gUnknown_82EBAC8
gUnknown_82EBAC8: @ 0x082EBAC8
	.incbin "baserom.gba", 0x2ebac8, 0x18
	.globl gUnknown_82EBAE0
gUnknown_82EBAE0: @ 0x082EBAE0
	.incbin "baserom.gba", 0x2ebae0, 0x50
	.globl gUnknown_82EBB30
gUnknown_82EBB30: @ 0x082EBB30
	.incbin "baserom.gba", 0x2ebb30, 0x8
	.globl gUnknown_82EBB38
gUnknown_82EBB38: @ 0x082EBB38
	.incbin "baserom.gba", 0x2ebb38, 0x150
