#!/usr/bin/env python3
import argparse
import re
from pathlib import Path


ROM_OFFSET = 0x5D3DFC
POINT_TYPES = (
    "MOVE_POINTS_COMBO",
    "MOVE_POINTS_STAT_RAISE",
    "MOVE_POINTS_STAT_LOWER",
    "MOVE_POINTS_RARE",
    "MOVE_POINTS_HEAL",
    "MOVE_POINTS_RISKY",
    "MOVE_POINTS_STATUS",
    "MOVE_POINTS_DMG",
    "MOVE_POINTS_DEF",
    "MOVE_POINTS_ACCURATE",
    "MOVE_POINTS_POWERFUL",
    "MOVE_POINTS_POPULAR",
    "MOVE_POINTS_LUCK",
    "MOVE_POINTS_STRONG",
    "MOVE_POINTS_LOW_PP",
    "MOVE_POINTS_EFFECT",
)


def read_move_names(path):
    pattern = re.compile(r"^\.set (MOVE_[A-Z0-9_]+|MOVES_COUNT), (\d+)$")
    names = {}
    moves_count = None
    for line in path.read_text(encoding="utf-8").splitlines():
        match = pattern.match(line)
        if match:
            name, value = match.groups()
            value = int(value)
            if name == "MOVES_COUNT":
                moves_count = value
            else:
                names[value] = name
    if moves_count is None:
        raise ValueError(f"MOVES_COUNT not found in {path}")
    expected = set(range(moves_count))
    if set(names) != expected:
        missing = sorted(expected - set(names))
        raise ValueError(f"move IDs are not contiguous; missing {missing[:8]}")
    return [names[index] for index in range(moves_count)]


def render(rom, move_names):
    size = len(move_names) * len(POINT_TYPES)
    data = rom[ROM_OFFSET:ROM_OFFSET + size]
    if len(data) != size:
        raise ValueError("ROM is too small for the Battle Dome move point table")
    invalid = [(index, value) for index, value in enumerate(data) if value not in (0, 1)]
    if invalid:
        raise ValueError(f"move point table contains a non-boolean value: {invalid[0]}")

    lines = [
        "@ Generated by tools/extract_battle_dome_move_points.py.",
        "@ Each mask identifies characteristics used to describe a trainer's battle style.",
    ]
    for move_id, move_name in enumerate(move_names):
        row = data[move_id * len(POINT_TYPES):(move_id + 1) * len(POINT_TYPES)]
        flags = [f"(1 << {name})" for name, enabled in zip(POINT_TYPES, row) if enabled]
        mask = " | ".join(flags) if flags else "0"
        lines.append(f"\tbattle_dome_move_points {move_name}, {mask}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("baserom.gba"))
    parser.add_argument("--moves", type=Path, default=Path("constants/moves.inc"))
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    output = render(args.input.read_bytes(), read_move_names(args.moves))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != output:
            raise SystemExit(f"{args.output} is not up to date")
        return
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
