#!/usr/bin/env python3
import argparse
from pathlib import Path


ROM_OFFSET = 0x5D5ECC
POINTER_TABLE_OFFSET = 0x5D678C
LENGTH_TABLE_OFFSET = 0x5D688C
ROM_BASE = 0x08000000
TRAINER_IDS_IN_TREE_ORDER = (0, 8, 12, 4, 7, 15, 11, 3, 2, 10, 14, 6, 5, 13, 9, 1)
ROUND_LENGTHS = (4, 7, 11, 13)
ROUND_STARTS = (0, 4, 11, 22)
SECTIONS_PER_TRAINER = sum(ROUND_LENGTHS)
SECTION_SIZE = 4


def render(rom):
    size = len(TRAINER_IDS_IN_TREE_ORDER) * SECTIONS_PER_TRAINER * SECTION_SIZE
    data = rom[ROM_OFFSET:ROM_OFFSET + size]
    if len(data) != size:
        raise ValueError("ROM is too small for the Battle Dome tourney line sections")

    trainer_to_slot = {
        trainer_id: slot for slot, trainer_id in enumerate(TRAINER_IDS_IN_TREE_ORDER)
    }
    for trainer_id in range(len(TRAINER_IDS_IN_TREE_ORDER)):
        slot = trainer_to_slot[trainer_id]
        for round_id, section_start in enumerate(ROUND_STARTS):
            pointer_offset = POINTER_TABLE_OFFSET + (trainer_id * 4 + round_id) * 4
            actual = int.from_bytes(rom[pointer_offset:pointer_offset + 4], "little")
            expected = ROM_BASE + ROM_OFFSET + (
                slot * SECTIONS_PER_TRAINER + section_start
            ) * SECTION_SIZE
            if actual != expected:
                raise ValueError(
                    f"line pointer mismatch for trainer {trainer_id}, round {round_id}: "
                    f"0x{actual:08X} != 0x{expected:08X}"
                )

        lengths_offset = LENGTH_TABLE_OFFSET + trainer_id * len(ROUND_LENGTHS)
        actual_lengths = tuple(rom[lengths_offset:lengths_offset + len(ROUND_LENGTHS)])
        if actual_lengths != ROUND_LENGTHS:
            raise ValueError(
                f"line lengths mismatch for trainer {trainer_id}: {actual_lengths}"
            )

    lines = [
        "@ Generated by tools/extract_battle_dome_tourney_tree_lines.py.",
        "@ Physical groups follow tournament-tree order; each round repeats the full path.",
    ]
    for slot, trainer_id in enumerate(TRAINER_IDS_IN_TREE_ORDER):
        lines.append("")
        lines.append(f"@ Tree slot {slot}, tournament trainer {trainer_id}.")
        trainer_start = slot * SECTIONS_PER_TRAINER
        for round_id, (round_start, round_length) in enumerate(
            zip(ROUND_STARTS, ROUND_LENGTHS), start=1
        ):
            lines.append(
                f"gBattleDomeTourneyTreeLineSections_Trainer{trainer_id}_Round{round_id}:"
            )
            for section_id in range(round_start, round_start + round_length):
                offset = (trainer_start + section_id) * SECTION_SIZE
                x = data[offset]
                y = data[offset + 1]
                tile = int.from_bytes(data[offset + 2:offset + 4], "little")
                lines.append(
                    f"\tbattle_dome_tourney_line_section {x}, {y}, 0x{tile:04X}"
                )
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=Path("baserom.gba"))
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    output = render(args.input.read_bytes())
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != output:
            raise SystemExit(f"{args.output} is not up to date")
        return
    args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
