#!/usr/bin/env python3
"""Extract the fixed-size Match Call rematch trainer table."""

import argparse
import re
import struct
from pathlib import Path


ROM_OFFSET = 0x5D6934
ENTRY_COUNT = 64
ENTRY_SIZE = 20
TRAINER_RE = re.compile(r"^@ Trainer (\d+): (.+)$")
SPECIAL_TRAINER_RE = re.compile(r"^@ 専用トレーナー (\d+): (.+)$")
SPECIAL_TRAINER_START = 520


def read_trainer_names(path: Path) -> dict[int, str]:
    names = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = TRAINER_RE.match(line)
        if match:
            names[int(match.group(1))] = match.group(2)
            continue
        match = SPECIAL_TRAINER_RE.match(line)
        if match:
            names[SPECIAL_TRAINER_START + int(match.group(1))] = match.group(2)
    return names


def render(rom_path: Path, trainers_path: Path) -> str:
    rom = rom_path.read_bytes()
    end = ROM_OFFSET + ENTRY_COUNT * ENTRY_SIZE
    if len(rom) < end:
        raise ValueError(f"ROM is too small for Match Call table ending at 0x{end:X}")

    names = read_trainer_names(trainers_path)
    lines = [
        "@ Generated by tools/extract_match_call_trainers.py.",
        "@ Message references are packed as (text group << 8) | one-based text index.",
        "",
    ]
    for index in range(ENTRY_COUNT):
        offset = ROM_OFFSET + index * ENTRY_SIZE
        values = struct.unpack_from("<10H", rom, offset)
        trainer_id, required_badges, *messages, padding = values
        if padding != 0:
            raise ValueError(f"entry {index} has nonzero padding 0x{padding:04X}")
        if len(messages) != 7:
            raise AssertionError("unexpected Match Call trainer field count")

        name = names.get(trainer_id, "unknown trainer")
        args = [f"0x{trainer_id:04X}", str(required_badges)]
        args.extend(f"0x{value:04X}" for value in messages)
        lines.append(
            f"@ Entry {index}, trainer {trainer_id}: {name} (ROM 0x{offset:06X})."
        )
        lines.append("\tmatch_call_trainer " + ", ".join(args))
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("rom", nargs="?", type=Path, default=Path("baserom.gba"))
    parser.add_argument(
        "--trainers",
        type=Path,
        default=Path("data/trainers/trainers.inc"),
        help="trainer source used only to add readable name comments",
    )
    parser.add_argument("--output", "-o", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    output = render(args.rom, args.trainers)
    if args.check:
        current = args.output.read_text(encoding="utf-8")
        if current != output:
            raise SystemExit(f"{args.output} is not up to date")
    else:
        args.output.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
