#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import struct
from pathlib import Path

ROM_BASE = 0x08000000
ENTRY_SIZE = 12

TYPE_NAMES = {
    0: "TYPE_NORMAL",
    1: "TYPE_FIGHTING",
    2: "TYPE_FLYING",
    3: "TYPE_POISON",
    4: "TYPE_GROUND",
    5: "TYPE_ROCK",
    6: "TYPE_BUG",
    7: "TYPE_GHOST",
    8: "TYPE_STEEL",
    9: "TYPE_MYSTERY",
    10: "TYPE_FIRE",
    11: "TYPE_WATER",
    12: "TYPE_GRASS",
    13: "TYPE_ELECTRIC",
    14: "TYPE_PSYCHIC",
    15: "TYPE_ICE",
    16: "TYPE_DRAGON",
    17: "TYPE_DARK",
}

_MOVE_RE = re.compile(
    r"^\s*\.set\s+MOVE_([A-Za-z0-9_]+)\s*,\s*(0x[0-9A-Fa-f]+|[0-9]+)\s*(?:@.*)?$"
)


def load_move_names(path: Path) -> dict[int, str]:
    names: dict[int, str] = {}
    if not path.exists():
        return names
    for line in path.read_text(encoding="utf-8").splitlines():
        match = _MOVE_RE.match(line)
        if match:
            name, value = match.groups()
            names[int(value, 0)] = f"MOVE_{name}"
    return names


def format_enum(value: int, names: dict[int, str], width: int = 2) -> str:
    return names.get(value, f"0x{value:0{width}X}")


def parse_entry(data: bytes, move_id: int) -> dict[str, int | bytes]:
    if len(data) != ENTRY_SIZE:
        raise ValueError(f"move {move_id}: expected {ENTRY_SIZE} bytes, got {len(data)}")

    effect, power, move_type, accuracy, pp, secondary_chance, target, priority, flags, padding = (
        struct.unpack("<7BbB3s", data)
    )
    return {
        "effect": effect,
        "power": power,
        "type": move_type,
        "accuracy": accuracy,
        "pp": pp,
        "secondary_chance": secondary_chance,
        "target": target,
        "priority": priority,
        "flags": flags,
        "padding": padding,
    }


def format_entry(move_name: str, entry: dict[str, int | bytes]) -> str:
    padding = bytes(entry["padding"])
    return "\n".join(
        [
            f"\t@ {move_name}",
            f"\t.byte 0x{int(entry['effect']):02X}",
            f"\t.byte {int(entry['power'])}",
            f"\t.byte {format_enum(int(entry['type']), TYPE_NAMES)}",
            f"\t.byte {int(entry['accuracy'])}",
            f"\t.byte {int(entry['pp'])}",
            f"\t.byte {int(entry['secondary_chance'])}",
            f"\t.byte 0x{int(entry['target']):02X}",
            f"\t.byte {int(entry['priority'])}",
            f"\t.byte 0x{int(entry['flags']):02X}",
            f"\t.byte 0x{padding[0]:02X}, 0x{padding[1]:02X}, 0x{padding[2]:02X}",
        ]
    )


def generate_inc(
    rom_data: bytes,
    table_rom_addr: int,
    count: int,
    move_names: dict[int, str],
) -> str:
    if table_rom_addr < ROM_BASE:
        raise ValueError(f"table address must be a ROM address >= 0x{ROM_BASE:08X}")

    table_offset = table_rom_addr - ROM_BASE
    table_size = count * ENTRY_SIZE
    table = rom_data[table_offset:table_offset + table_size]
    if len(table) != table_size:
        raise ValueError(
            f"ROM is too short: expected {table_size} bytes at 0x{table_rom_addr:08X}, "
            f"got {len(table)}"
        )

    lines = [
        "@ Generated by tools/extract_battle_moves.py. Do not edit by hand.",
        "@ Fields: Effect, Power, Type, Accuracy, PP, SecondaryEffectChance,",
        "@ Target, Priority, Flags, Padding[3]",
        '.include "constants/type_constants.inc"',
        "",
        ".globl gBattleMoves",
        f"gBattleMoves: @ 0x{table_rom_addr:08X}",
        "",
    ]

    for move_id in range(count):
        start = move_id * ENTRY_SIZE
        entry = parse_entry(table[start:start + ENTRY_SIZE], move_id)
        move_name = move_names.get(move_id, f"MOVE_INTERNAL_{move_id}")
        lines.extend([format_entry(move_name, entry), ""])

    return "\n".join(lines).rstrip() + "\n"


def verify_round_trip(
    rom_data: bytes,
    table_rom_addr: int,
    count: int,
) -> None:
    table_offset = table_rom_addr - ROM_BASE
    original = rom_data[table_offset:table_offset + count * ENTRY_SIZE]
    if len(original) != count * ENTRY_SIZE:
        raise ValueError("ROM is too short for the requested move table")

    rebuilt = bytearray()
    for move_id in range(count):
        start = move_id * ENTRY_SIZE
        entry = parse_entry(original[start:start + ENTRY_SIZE], move_id)
        rebuilt.extend(
            [
                int(entry["effect"]),
                int(entry["power"]),
                int(entry["type"]),
                int(entry["accuracy"]),
                int(entry["pp"]),
                int(entry["secondary_chance"]),
                int(entry["target"]),
            ]
        )
        rebuilt.extend(struct.pack("<b", int(entry["priority"])))
        rebuilt.append(int(entry["flags"]))
        rebuilt.extend(bytes(entry["padding"]))

    if bytes(rebuilt) != original:
        raise RuntimeError("internal round-trip validation failed")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Extract the fixed-size battle move table from the Japanese Emerald ROM"
    )
    parser.add_argument("--rom", default="baserom.gba")
    parser.add_argument(
        "--address",
        required=True,
        type=lambda value: int(value, 0),
        help="ROM address of gBattleMoves, for example 0x08XXXXXX",
    )
    parser.add_argument(
        "--count",
        required=True,
        type=int,
        help="number of 12-byte move entries to extract",
    )
    parser.add_argument("--output", default="data/pokemon/battle_moves.inc")
    parser.add_argument("--moves", default="constants/move_constants.inc")
    args = parser.parse_args()

    if args.count <= 0:
        parser.error("--count must be greater than zero")

    root = Path(__file__).resolve().parent.parent
    rom_data = (root / args.rom).read_bytes()
    verify_round_trip(rom_data, args.address, args.count)
    output = generate_inc(
        rom_data,
        args.address,
        args.count,
        load_move_names(root / args.moves),
    )

    output_path = root / args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8")

    table_size = args.count * ENTRY_SIZE
    print(f"generated: {output_path}")
    print(f"entries: {args.count}, bytes: {table_size} (0x{table_size:X})")
    print(f"address: 0x{args.address:08X}")
    print("raw round-trip: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
