	@ src/data/easy_chat/easy_chat_group_people.h:136 easy_chat_group_people_line_136
	.globl gText_Rom_57578F
gText_Rom_57578F: @ 0x0857578F
	.string "ガール{EOS}"
	.if (. - gText_Rom_57578F) > 0x4
	.error "gText_Rom_57578F may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_57578F) < 0x4
	.space 0x4 - (. - gText_Rom_57578F)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:142 easy_chat_group_people_line_142
	.globl gText_Rom_575793
gText_Rom_575793: @ 0x08575793
	.string "かぞく{EOS}"
	.if (. - gText_Rom_575793) > 0x4
	.error "gText_Rom_575793 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_575793) < 0x4
	.space 0x4 - (. - gText_Rom_575793)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:148 easy_chat_group_people_line_148
	.globl gText_Rom_575797
gText_Rom_575797: @ 0x08575797
	.string "かのじょ{EOS}"
	.if (. - gText_Rom_575797) > 0x5
	.error "gText_Rom_575797 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_575797) < 0x5
	.space 0x5 - (. - gText_Rom_575797)
	.endif
	@ Decoded text from ROM range: offset=0x57579C, size=0x6
	.string "かれ{EOS}"
	.string "きみ{EOS}"

	@ src/data/easy_chat/easy_chat_group_people.h:166 easy_chat_group_people_line_166
	.globl gText_Rom_5757A2
gText_Rom_5757A2: @ 0x085757A2
	.string "きみが{EOS}"
	.if (. - gText_Rom_5757A2) > 0x4
	.error "gText_Rom_5757A2 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757A2) < 0x4
	.space 0x4 - (. - gText_Rom_5757A2)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:172 easy_chat_group_people_line_172
	.globl gText_Rom_5757A6
gText_Rom_5757A6: @ 0x085757A6
	.string "きみに{EOS}"
	.if (. - gText_Rom_5757A6) > 0x4
	.error "gText_Rom_5757A6 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757A6) < 0x4
	.space 0x4 - (. - gText_Rom_5757A6)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:178 easy_chat_group_people_line_178
	.globl gText_Rom_5757AA
gText_Rom_5757AA: @ 0x085757AA
	.string "きみの{EOS}"
	.if (. - gText_Rom_5757AA) > 0x4
	.error "gText_Rom_5757AA may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757AA) < 0x4
	.space 0x4 - (. - gText_Rom_5757AA)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:184 easy_chat_group_people_line_184
	.globl gText_Rom_5757AE
gText_Rom_5757AE: @ 0x085757AE
	.string "きみは{EOS}"
	.if (. - gText_Rom_5757AE) > 0x4
	.error "gText_Rom_5757AE may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757AE) < 0x4
	.space 0x4 - (. - gText_Rom_5757AE)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:190 easy_chat_group_people_line_190
	.globl gText_Rom_5757B2
gText_Rom_5757B2: @ 0x085757B2
	.string "きみを{EOS}"
	.if (. - gText_Rom_5757B2) > 0x4
	.error "gText_Rom_5757B2 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757B2) < 0x4
	.space 0x4 - (. - gText_Rom_5757B2)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:196 easy_chat_group_people_line_196
	.globl gText_Rom_5757B6
gText_Rom_5757B6: @ 0x085757B6
	.string "きょうだい{EOS}"
	.if (. - gText_Rom_5757B6) > 0x6
	.error "gText_Rom_5757B6 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757B6) < 0x6
	.space 0x6 - (. - gText_Rom_5757B6)
	.endif
	@ Decoded text from ROM range: offset=0x5757BC, size=0x3
	.string "くん{EOS}"

	@ src/data/easy_chat/easy_chat_group_people.h:208 easy_chat_group_people_line_208
	.globl gText_Rom_5757BF
gText_Rom_5757BF: @ 0x085757BF
	.string "こども{EOS}"
	.if (. - gText_Rom_5757BF) > 0x4
	.error "gText_Rom_5757BF may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757BF) < 0x4
	.space 0x4 - (. - gText_Rom_5757BF)
	.endif
	@ Decoded text from ROM range: offset=0x5757C3, size=0x6
	.string "さま{EOS}"
	.string "さん{EOS}"

	@ src/data/easy_chat/easy_chat_group_people.h:226 easy_chat_group_people_line_226
	.globl gText_Rom_5757C9
gText_Rom_5757C9: @ 0x085757C9
	.string "じぶん{EOS}"
	.if (. - gText_Rom_5757C9) > 0x4
	.error "gText_Rom_5757C9 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757C9) < 0x4
	.space 0x4 - (. - gText_Rom_5757C9)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:232 easy_chat_group_people_line_232
	.globl gText_Rom_5757CD
gText_Rom_5757CD: @ 0x085757CD
	.string "じぶんが{EOS}"
	.if (. - gText_Rom_5757CD) > 0x5
	.error "gText_Rom_5757CD may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757CD) < 0x5
	.space 0x5 - (. - gText_Rom_5757CD)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:238 easy_chat_group_people_line_238
	.globl gText_Rom_5757D2
gText_Rom_5757D2: @ 0x085757D2
	.string "じぶんに{EOS}"
	.if (. - gText_Rom_5757D2) > 0x5
	.error "gText_Rom_5757D2 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757D2) < 0x5
	.space 0x5 - (. - gText_Rom_5757D2)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:244 easy_chat_group_people_line_244
	.globl gText_Rom_5757D7
gText_Rom_5757D7: @ 0x085757D7
	.string "じぶんの{EOS}"
	.if (. - gText_Rom_5757D7) > 0x5
	.error "gText_Rom_5757D7 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757D7) < 0x5
	.space 0x5 - (. - gText_Rom_5757D7)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:250 easy_chat_group_people_line_250
	.globl gText_Rom_5757DC
gText_Rom_5757DC: @ 0x085757DC
	.string "じぶんは{EOS}"
	.if (. - gText_Rom_5757DC) > 0x5
	.error "gText_Rom_5757DC may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757DC) < 0x5
	.space 0x5 - (. - gText_Rom_5757DC)
	.endif

	@ src/data/easy_chat/easy_chat_group_people.h:256 easy_chat_group_people_line_256
	.globl gText_Rom_5757E1
gText_Rom_5757E1: @ 0x085757E1
	.string "じぶんを{EOS}"
	.if (. - gText_Rom_5757E1) > 0x5
	.error "gText_Rom_5757E1 may not grow beyond its original slot"
	.endif
	.if (. - gText_Rom_5757E1) < 0x5
	.space 0x5 - (. - gText_Rom_5757E1)
	.endif
	@ Decoded text from ROM range: offset=0x5757E6, size=0x3
	.string "だれ{EOS}"

