	.4byte gText_Rom_5C96DB
	.4byte gText_Rom_5C96E1
	.4byte gText_Rom_5C96E6
	.4byte gText_Rom_5C96EE
	.4byte gText_Rom_5C96DB
	.4byte gText_Rom_5C96DB
	.4byte gText_Rom_5C96F3
	.4byte gText_Rom_5C96DB
	.4byte gText_Rom_5C96DB
	.4byte gText_Rom_5C96DB
	.4byte gText_Rom_5C96E1
	.4byte gText_Rom_5C96F3
	.4byte gText_Rom_5C96DB
	.4byte gText_Rom_5C96E1
	.4byte gText_Rom_5C96E6
	.4byte gText_Rom_5C96DB
	.globl gText_Rom_5C9738

